---
tilesets:
  - id: brush_no_hiding
    biomes:
      - types: [grass,tropical, ice, desert, flower]
        spriteSheet: terrain_tilesets
        spriteBase: brush_no_hiding
        battleBackgroundSpriteSheet: backgrounds/map_backgrounds_RagnarokMod
        battleBackgroundSprite: street_background
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_building.png"
        infoScreenOffset: 0
        fillColour: '#2a2542'
      - types: [volcano]
        spriteSheet: terrain_tilesets
        spriteBase: brush_no_hiding
        battleBackgroundSpriteSheet: backgrounds/map_backgrounds_RagnarokMod
        battleBackgroundSprite: street_background
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_building.png"
        infoScreenOffset: 0
        fillColour: '#76231c'
    primaryConnect: []
    decayTo: brush
    tilesGroups:
      - tiles:
        - { x: 0, y: 0 }
...