---
tilesets:
  - id: brush
    primaryConnect: []
    decayTo: plains
    biomes:
      - types: [grass]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_forest
        battleBackgroundSpriteSheet: backgrounds/grass_battlescreen_extendedbackgrounds
        battleBackgroundSprite: grass_battlescreen_extendedbackgrounds_forest
        battleBackgroundSpriteForeground: grass_battlescreen_extendedbackgrounds_forest_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Forest
        fillColour: '#7fa33b'
      - types: [tropical]
        minRandomElements: 3
        maxRandomElements: 4
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_forest
        battleBackgroundSpriteSheet: backgrounds/grass_battlescreen_extendedbackgrounds
        battleBackgroundSprite: grass_battlescreen_extendedbackgrounds_forest
        battleBackgroundSpriteForeground: grass_battlescreen_extendedbackgrounds_forest_foreground
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_forest_tropical.png"
        fillColour: '#7fa33b'
        randomElements:
          - sprite: terrain/trees/desert/shrub_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small

      - types: [ice]
        minRandomElements: 3
        maxRandomElements: 4
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_snow_forest
        battleBackgroundSpriteSheet: backgrounds/snow_battlescreen_extendedbackgrounds
        battleBackgroundSprite: snow_battlescreen_extendedbackgrounds_forest
        battleBackgroundSpriteForeground: snow_battlescreen_extendedbackgrounds_forest_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Forest
        fillColour: '#aec6e3'
        randomElements:
          - sprite: terrain/trees/desert/shrub_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small

      - types: [desert]
        minRandomElements: 3
        maxRandomElements: 4
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_sand_forest
        battleBackgroundSpriteSheet: backgrounds/sand_battlescreen_extendedbackgrounds
        battleBackgroundSprite: sand_battlescreen_extendedbackgrounds_forest
        battleBackgroundSpriteForeground: sand_battlescreen_extendedbackgrounds_forest_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Forest
        fillColour: '#987647'
        randomElements:
          - sprite: terrain/trees/desert/shrub_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small
      - types: [volcano]
        minRandomElements: 3
        maxRandomElements: 4
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_sand_forest
        battleBackgroundSpriteSheet: backgrounds/volcano_battlescreen_extendedbackgrounds
        battleBackgroundSprite: volcano_battlescreen_extendedbackgrounds_forest
        battleBackgroundSpriteForeground: volcano_battlescreen_extendedbackgrounds_forest_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Forest
        fillColour: '#6d5e56'
        randomElements:
          - sprite: terrain/trees/desert/shrub_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small
...