---
tilesets:
  - id: building
    biomes:
      - types: [grass,tropical, ice, desert]
        spriteSheet: tilesets
        spriteBase: deck_tileset
        battleBackgroundSpriteSheet: backgrounds/map_backgrounds_RagnarokMod
        battleBackgroundSprite: street_background
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_building.png"
        infoScreenOffset: 0
        fillColour: '#2a2542'
      - types: [volcano]
        spriteSheet: tilesets
        spriteBase: deck_tileset
        battleBackgroundSpriteSheet: backgrounds/map_backgrounds_RagnarokMod
        battleBackgroundSprite: street_background
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_building.png"
        infoScreenOffset: 0
        fillColour: '#76231c'
    primaryConnect: []
    decayTo: street

...