---
tilesets:
  - id: mangrove
    primaryConnect: []
    decayTo: river
    biomes:
      - types: [grass,tropical]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_ocean
        battleBackgroundSpriteSheet: backgrounds/map_backgrounds_RagnarokMod
        battleBackgroundSprite: tropical_mangrove_background
        battleBackgroundSpriteForeground: tropical_mangrove_foreground
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_mangrove.png"
        infoScreenOffset: 70
        fillColour: '#286ab1'
      - types: [ice]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_snow_river
        battleBackgroundSpriteSheet: backgrounds/snow_battlescreen_extendedbackgrounds
        battleBackgroundSprite: snow_battlescreen_extendedbackgrounds_river
        battleBackgroundSpriteForeground: snow_battlescreen_extendedbackgrounds_river_foreground
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_mangrove.png"
        infoScreenOffset: 70
        fillColour: '#1659a8'
      - types: [desert]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_sand_river
        battleBackgroundSpriteSheet: backgrounds/sand_battlescreen_extendedbackgrounds
        battleBackgroundSprite: sand_battlescreen_extendedbackgrounds_river
        battleBackgroundSpriteForeground: sand_battlescreen_extendedbackgrounds_river_foreground
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_mangrove.png"
        infoScreenOffset: 70
        fillColour: '#1659a8'
      - types: [volcano]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_sand_river
        battleBackgroundSpriteSheet: backgrounds/volcano_battlescreen_extendedbackgrounds
        battleBackgroundSprite: volcano_battlescreen_extendedbackgrounds_lava
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_mangrove.png"
        infoScreenOffset: 70
        fillColour: '#76231c'
...
