---
tilesets:
  - id: mangrove
    primaryConnect: []
    decayTo: river
    biomes:
      - types: [grass,tropical]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_ocean
        battleBackgroundSpriteSheet: backgrounds/grass_battlescreen_extendedbackgrounds
        battleBackgroundSprite: grass_battlescreen_extendedbackgrounds_river
        battleBackgroundSpriteForeground: grass_battlescreen_extendedbackgrounds_river_foreground
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_mangrove.png"
        infoScreenOffset: 70
        fillColour: '#286ab1'
      - types: [ice]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_snow_river
        battleBackgroundSpriteSheet: backgrounds/snow_battlescreen_extendedbackgrounds
        battleBackgroundSprite: snow_battlescreen_extendedbackgrounds_river
        battleBackgroundSpriteForeground: snow_battlescreen_extendedbackgrounds_river_foreground
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_mangrove.png"
        infoScreenOffset: 70
        fillColour: '#1659a8'
        minRandomElements: 2
        maxRandomElements: 3
        randomElements:
          - sprite: terrain/trees/desert/palm_small
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small

          - sprite: terrain/trees/desert/palm_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_medium

          - sprite: terrain/trees/desert/palm_big
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_large

          - sprite: terrain/trees/grass/round_small
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small

          - sprite: terrain/trees/grass/round_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_medium

          - sprite: terrain/trees/grass/round_big
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_large

          - sprite: terrain/trees/desert/shrub_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small
      - types: [desert]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_sand_river
        battleBackgroundSpriteSheet: backgrounds/sand_battlescreen_extendedbackgrounds
        battleBackgroundSprite: sand_battlescreen_extendedbackgrounds_river
        battleBackgroundSpriteForeground: sand_battlescreen_extendedbackgrounds_river_foreground
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_mangrove.png"
        infoScreenOffset: 70
        fillColour: '#1659a8'
        minRandomElements: 2
        maxRandomElements: 4
        randomElements:
          - sprite: terrain/trees/desert/palm_small
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small

          - sprite: terrain/trees/desert/palm_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_medium

          - sprite: terrain/trees/desert/palm_big
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_large

          - sprite: terrain/trees/grass/round_small
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small

          - sprite: terrain/trees/grass/round_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_medium

          - sprite: terrain/trees/grass/round_big
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_large

          - sprite: terrain/trees/desert/shrub_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small
      - types: [volcano]
        portraitSpriteSheet: terrain/terrain_portraits
        portraitSprite: terrain_portraits_sand_river
        battleBackgroundSpriteSheet: backgrounds/volcano_battlescreen_extendedbackgrounds
        battleBackgroundSprite: volcano_battlescreen_extendedbackgrounds_lava
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_mangrove.png"
        infoScreenOffset: 70
        fillColour: '#76231c'
        minRandomElements: 2
        maxRandomElements: 4
        randomElements:
          - sprite: terrain/trees/desert/palm_small
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small

          - sprite: terrain/trees/desert/palm_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_medium

          - sprite: terrain/trees/desert/palm_big
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_large

          - sprite: terrain/trees/grass/round_small
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small

          - sprite: terrain/trees/grass/round_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_medium

          - sprite: terrain/trees/grass/round_big
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_large

          - sprite: terrain/trees/desert/shrub_medium
            shadowSpriteSheet: fx/shadows
            shadowSprite: shadows_small
...
