---
tilesets:
  - id: brush_invis_icon
    biomes:
      - types: [grass, jungle, desert, ice, arctic, arctic_blood, dungeon, dungeon_lava, dungeon_purple, tundra, flower, deepforest, ice_low, arctic_bloom]
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_brush_invis.png"
  - id: invisibleBlockerOcean_icon
    biomes:
      - types: [grass, jungle, desert, ice, arctic, arctic_blood, dungeon, dungeon_lava, dungeon_purple, tundra, flower, deepforest, ice_low, arctic_bloom]
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_blocker_ocean.png"
  - id: invisibleWallOcean_icon
    biomes:
      - types: [grass, jungle, desert, ice, arctic, arctic_blood, dungeon, dungeon_lava, dungeon_purple, tundra, flower, deepforest, ice_low, arctic_bloom]
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_hull_ocean.png"
  - id: invisibleWallSea_icon
    biomes:
      - types: [grass, jungle, desert, ice, arctic, arctic_blood, dungeon, dungeon_lava, dungeon_purple, tundra, flower, deepforest, ice_low, arctic_bloom]
        iconSpriteSheet: ui_RagnarokMod
        iconSprite: ":img:ui/codex/icons/icon_terrain_hull_sea.png"
...