---
tilesets:
  - id: reef
    type: WangBlob
    biomes:
      - types: [grass, flower, deepforest]
        spriteSheet: tilesets
        spriteBase: wang_grass_reef_tileset_000
        waterSpriteBase: wang_grass_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/grass_battlescreen_extendedbackgrounds
        battleBackgroundSprite: grass_battlescreen_extendedbackgrounds_reef
        battleBackgroundSpriteForeground: grass_battlescreen_extendedbackgrounds_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
      - types: [dungeon, dungeon_purple]
        spriteSheet: tilesets
        spriteBase: wang_dungeon_reef_tileset_000
        waterSpriteBase: wang_dungeon_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/dungeon_battlescreen_extendedbackgrounds
        battleBackgroundSprite: dungeon_battlescreen_extendedbackgrounds_reef
        battleBackgroundSpriteForeground: dungeon_battlescreen_extendedbackgrounds_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
      - types: [dungeon_lava]
        spriteSheet: tilesets
        spriteBase: wang_dungeon_lava_reef_tileset_000
        waterSpriteBase: wang_dungeon_lava_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/dungeon_lava_battlescreen_extendedbackgrounds
        battleBackgroundSprite: dungeon_lava_battlescreen_extendedbackgrounds_reef
        battleBackgroundSpriteForeground: dungeon_lava_battlescreen_extendedbackgrounds_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
      - types: [desert]
        spriteSheet: tilesets
        spriteBase: wang_desert_reef_tileset_000
        waterSpriteBase: wang_desert_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/desert_battlescreen_extendedbackgrounds
        battleBackgroundSprite: desert_battlescreen_extendedbackgrounds_reef
        battleBackgroundSpriteForeground: desert_battlescreen_extendedbackgrounds_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
      - types: [ice, ice_low]
        spriteSheet: tilesets
        spriteBase: wang_ice_reef_tileset_000
        waterSpriteBase: wang_ice_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/ice_battlescreen_extendedbackgrounds
        battleBackgroundSprite: ice_battlescreen_extendedbackgrounds_reef
        battleBackgroundSpriteForeground: ice_battlescreen_extendedbackgrounds_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
      - types: [arctic]
        spriteSheet: tilesets
        spriteBase: wang_arctic_reef_tileset_000
        waterSpriteBase: wang_arctic_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/arctic_battlescreen_extendedbackgrounds
        battleBackgroundSprite: arctic_battlescreen_extendedbackgrounds_reef
        battleBackgroundSpriteForeground: arctic_battlescreen_extendedbackgrounds_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
      - types: [arctic_bloom]
        spriteSheet: tilesets
        spriteBase: wang_arctic_reef_tileset_000
        waterSpriteBase: wang_arctic_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/arctic_battlescreen_extendedbackgrounds_bloom
        battleBackgroundSprite: arctic_battlescreen_extendedbackgrounds_bloom_reef
        battleBackgroundSpriteForeground: arctic_battlescreen_extendedbackgrounds_bloom_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
      - types: [arctic_blood]
        spriteSheet: tilesets
        spriteBase: wang_arctic_reef_tileset_000
        waterSpriteBase: wang_arctic_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/arctic_battlescreen_extendedbackgrounds_red
        battleBackgroundSprite: arctic_battlescreen_extendedbackgrounds_red_reef
        battleBackgroundSpriteForeground: arctic_battlescreen_extendedbackgrounds_red_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
      - types: [jungle]
        spriteSheet: tilesets
        spriteBase: wang_jungle_reef_tileset_000
        waterSpriteBase: wang_jungle_reef_tileset_001
        battleBackgroundSpriteSheet: backgrounds/jungle_battlescreen_extendedbackgrounds
        battleBackgroundSprite: jungle_battlescreen_extendedbackgrounds_reef
        battleBackgroundSpriteForeground: jungle_battlescreen_extendedbackgrounds_reef_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_Reef
        infoScreenOffset: 30
        fillColour: '#2a2542'
    primaryConnect: [undefined, reef, cave_reef]
    decayTo: sea
    extras:
    # Single tile variation
      - { x: 6, y: 7, mask: 256 }
      - { x: 6, y: 8, mask: 256 }
      - { x: 6, y: 9, mask: 256 }
      - { x: 3, y: 8, mask: 255 }
      - { x: 3, y: 9, mask: 255 }
      - { x: 3, y: 10, mask: 255 }
      - { x: 1, y: 10, mask: 255 }
      - { x: 2, y: 10, mask: 255 }

    # Corner tile variation
      - { x: 0, y: 7, mask: 28 }
      - { x: 4, y: 7, mask: 112 }
      - { x: 0, y: 11, mask: 7 }
      - { x: 4, y: 11, mask: 193 }
    # Outer corner tile variation
      - { x: 1, y: 8, mask: 247 }
      - { x: 2, y: 8, mask: 223 }
      - { x: 1, y: 9, mask: 253 }
      - { x: 2, y: 9, mask: 127 }
    # Side tile variation
      - { x: 1, y: 7, mask: 124 }
      - { x: 2, y: 7, mask: 124 }
      - { x: 3, y: 7, mask: 124 }

      - { x: 0, y: 8, mask: 31 }
      - { x: 0, y: 9, mask: 31 }
      - { x: 0, y: 10, mask: 31 }

      - { x: 4, y: 8, mask: 241 }
      - { x: 4, y: 9, mask: 241 }
      - { x: 4, y: 10, mask: 241 }

      - { x: 1, y: 11, mask: 199 }
      - { x: 2, y: 11, mask: 199 }
      - { x: 3, y: 11, mask: 199 }
    # U-shaped 1 tile wide ending variation
      - { x: 0, y: 12, mask: 4 }
      - { x: 4, y: 12, mask: 64 }
      - { x: 5, y: 7, mask: 16 }
      - { x: 5, y: 11, mask: 1 }
    # Parallel 1 tile beach river variation
      - { x: 1, y: 12, mask: 68 }
      - { x: 2, y: 12, mask: 68 }
      - { x: 3, y: 12, mask: 68 }

      - { x: 5, y: 8, mask: 17 }
      - { x: 5, y: 9, mask: 17 }
      - { x: 5, y: 10, mask: 17 }
...