---
tilesets:
  - id: undefined
    primaryConnect: []
    biomes:
      - types: [grass, tropical, jungle, desert, ice, arctic, arctic_blood, dungeon, dungeon_lava, dungeon_purple, tundra, flower, deepforest, ice_low, arctic_bloom]
...