---

# This is the string configuration file for English.
en-GB:
  #AI
  ai_profile_rival_pirate: Rival Pirate
  ai_profile_coward: Coward
  ai_profile_charge: Charge
  ai_profile_mangrove_madness: Mangrove Madness
  ai_profile_city_passive: City Passive
  ai_profile_city_war: City War

  # Merge Verb
  ui_unit_verbs_better_merge: Merge
  ui_unit_verbs_pirate_deposit: Deposit
  ui_unit_verbs_pirate_steal: Steal
  ui_unit_verbs_board: Board
  ui_unit_verbs_hand_over_crown: Hand Over Crown
  ui_unit_verbs_pick_up_crown: Pick Up Crown
  ui_unit_verbs_throw_crown: Throw Crown
  ui_unit_verbs_spawn_flare_1: Spawn Flare[1]
  ui_unit_verbs_spawn_flare_2: Spawn Flare[2]
  ui_unit_verbs_spawn_flare_many: Spawn Flare[3+]
  ui_unit_verbs_healing_potion: Use Potion
  ui_unit_verbs_claim: Retrieve
  ui_unit_verbs_rescue: Rescue
  ui_unit_verbs_hire: Hire
  ui_unit_verbs_upgrade: Retrain
  
  #biomes
  biome_name_tropical: Tropical
  
  #terrain
  terrain_name_rough: Cave
  terrain_description_rough: Only ground units can enter.
  terrain_name_deck: Deck
  terrain_description_deck: The deck provides small amount of defense and doesn't impede the movement of any ground units.
  
  terrain_name_hull: Hull
  terrain_name_cabin: Cabin Walls
  terrain_description_invisible_wall_sea: The hull of the ship is unscalable by normal means, but still lets flyers pass over.
  terrain_description_invisible_wall_ocean: The hull of the ship is unscalable by normal means, but still lets flyers pass over.
  terrain_description_invisible_blocker_ocean: The cabin walls prevents all units from passing.
  terrain_description_sea_alt: Open water. Accessible only to air and naval units.
  terrain_description_river: Slows down land units. Units attacked in a river are at a distinct disadvantage.
  terrain_name_mangrove: Mangrove
  terrain_description_mangrove: Conceals units, but it is incredibly slow to traverse for both naval and ground units.
  terrain_description_plains_alt: Whilst accessible to all units, plains provide little defence.
  terrain_description_forest_alt: Forests are slow going, but provide good defence and a means of avoiding vehicles
  terrain_name_cave_reef: Cove Reef
  terrain_description_cave_reef: "Cove Reefs provide the highest amount of defense possible for naval units, but slows down movement."
  terrain_name_cave_sea: Cove
  terrain_description_cave_sea: "Accessible only to naval units. Provides defense comparable to reefs in the open sea, but does not conceal."
  terrain_name_cave_beach: Cove Beach
  terrain_description_cave_beach: "Accessible to naval and walking units. Cove Beaches provides no defense."
  terrain_name_cave_bridge: Cove Bridge
  terrain_description_cave_bridge: "Cove Bridges allow ground units to travel over otherwise impassable waters."
  terrain_name_cave_wall: Cave Wall
  terrain_description_cave_wall: "Blocks all units."
  terrain_name_cave_river: Cave River
  terrain_description_cave_river: Slows down land units. Units attacked in a river are at a disadvantage.
  terrain_name_brush: Field
  terrain_description_brush: Fields provides limited defense. Cavalry and wheeled units are slowed.
  terrain_description_brush_invis: Fields provides limited defense. Cavalry and wheeled units are slowed.
  terrain_name_cave_road: Cave Road
  terrain_description_cave_road: Underground roads speeds along wheeled units, but only provide limited defense.
  terrain_name_street: Road
  terrain_description_street: Urban roads that speed along big wooden wheels, but offer little protection.
  terrain_name_building: Building
  terrain_description_building: Buildings so densely packed they act as walls for units.
  terrain_name_quay: Sea
  terrain_description_quay: Open water. Accessible only to air and naval units.
  terrain_description_bridge_wide: Bridges allow wheeled vehicles to travel quickly over otherwise impassable waters.


  #Fog of war gimmick tiles
  terrain_description_forest_no_hiding: Forests are slow going, but provide good defence and a means of avoiding vehicles
  terrain_description_forest_alt_no_hiding: Forests are slow going, but provide good defence and a means of avoiding vehicles
  terrain_description_mountain_no_blocking: "Accessible only to walking and air units. Slow going, but confers high defence."
  terrain_description_reef_no_hiding: "Rocks that lie beneath the sea, slowing but also protecting naval units."
  terrain_description_wall_no_blocking: "While projectiles can travel over walls, units are unable to."
  
  terrain_name_deck: Deck
  terrain_name_outlaw_ship: Outlaw Ship
  terrain_name_outlaw_cherry_ship: Outlaw and Cherry Ship
  
  biome_name_tropical: "Tropical"
  world_map_aurania_zoomed_name: "Aurania Zoomed"
  
  #units
  
  unit_class_name_flagship_wulfar: "Wulfar's Flagship"
  unit_name_flagship_wulfar: "Wulfar's Flagship"
  unit_description_commander_flagship_wulfar: "Flagship of Wulfar"
  
  unit_class_name_flagship_rival: "Rival's Flagship"
  unit_name_flagship_rival: "Rival's Flagship"
  unit_description_commander_flagship_rival: "Flagship of Rival"



  # Commander
  character_flagship_wulfar_name: "Wulfar's Flagship"
  character_flagship_wulfar_title: "Captain Wulfar"
  
  groove_name_broadside: "Broadside"
  groove_description_broadside: "Blasts enemies in a cone. The closest enemies take 100% of the commanders damage at full health, the next layer 66% and the furthest layer 33%."
  groove_name_all_caps_groove_broadside: "BROADSIDE"
  
  character_rival_name: "Rival"
  character_rival_title: "Captain Rival"
  
  character_duchess_name: "Sabah"
  character_duchess_title: "The Duchess of Dorne"
  unit_description_commander_duchess: "Duchess of Dorne. She commands her units to strike first when attacked."


  character_rival_name: "Rival"
  character_rival_title: "Captain Rival"

  groove_name_alert_area: "Martial Law"
  groove_description_alert_area: "Permanently alerts allies in a radius of 2."
  groove_name_all_caps_groove_alert_area: "MARTIAL LAW"


  groove_name_morale_boost: "En Garde"
  groove_description_morale_boost: "Friendly units within 2 tiles strike first when attacked."
  groove_name_all_caps_groove_morale_boost: "EN GARDE"

  character_generic_outlaw_gang_name: "Outlaw Gang"
  character_generic_vesper_gang_name: "Vespers Gang"
  character_villager_neutral_name: "Villager Neutral"
  
  
  
  groove_name_area_damage_rival: "Fire bombs"
  groove_description_area_damage_rival: "Sets an area ablaze over several turns."
  groove_name_all_caps_groove_area_damage_rival: "FIRE BOMBS"
  
  unit_class_name_cart: Cart
  unit_description_cart: "A humble cart."
  unit_name_cart_cherrystone: Cart
  
  unit_class_name_flare: Flare
  unit_description_flare: Reveals hidden units in an area. It expires at the end of the turn.
  unit_name_flare: Flare

  unit_class_name_crew: Capsized Crew
  unit_description_crew: "Crew drifting at sea. Save them, and maybe they can help you in return."
  unit_name_crew: Capsized Crew
  
  unit_class_name_rival: Ol' Friend
  unit_description_rival: "Ranged ground units able to move and attack in the same turn. Critical hit when stationary."
  unit_name_rival: Ol' Friend
  

  unit_name_archer_outlaws: Poacher 
  unit_name_dog_outlaws: Stray
  unit_name_mage_outlaws: Trickster 
  unit_name_rifleman_outlaws: Sharpshooter 
  unit_name_soldier_outlaws: Cutthroat
  unit_name_spearman_outlaws: Brigand 
  unit_name_knight_outlaws: Highwayman 
  unit_name_wagon_outlaws: Wagon
  unit_name_warship_outlaws: Warship 
  unit_name_harpoonship_outlaws: Harpoon Ship 
  unit_name_dragon_outlaws: Emberwing 
  unit_name_trebuchet_outlaws: Trebuchet 
  unit_name_merman_outlaws: Corsair
  unit_name_turtle_outlaws: Seadog 
  unit_name_witch_outlaws: Hag 
  unit_name_harpy_outlaws: Harpy 
  unit_name_balloon_outlaws: Balloon 
  unit_name_giant_outlaws: Golem 
  unit_name_ballista_outlaws: Ballista 
  unit_name_travelboat_outlaws: Barge
  unit_name_villager_outlaws: Beggar 
  unit_name_thief_cherrystone: Tax Collector
  unit_name_thief_outlaws: Smuggler
  unit_name_rifleman_outlaws: Sharpshooter 
  unit_name_rival_outlaws: Ol'Friend 

  structure_name_tavern: "Tavern"
  unit_description_tavern: "Neutral building where anyone can reinforce and retrain their units."  


  # UNIT DESCRIPTIONS
  unit_description_soldier: "[MELEE] Basic infantry, useful for capturing structures. Critical hit when adjacent to its commander."
  unit_description_villager: "Simple peasants. They're not equipped to fight, and are vulnerable to just about everything."
  unit_description_spearman: "[MELEE] Slower, more powerful infantry. Critical hit when adjacent to another spearman."
  unit_description_archer: "Ranged ground units able to move and attack in the same turn. Critical hit when stationary."
  unit_description_dog: "[MELEE] A quick unit. Critical hit when another dog unit is adjacent to the target."
  unit_description_mage: "A powerful unit built to combat naval and air units. Critical hit when defence is 3 or above. Able to heal allied targets by 20%."
  unit_description_warship: "An immensely powerful long range unit. Critical hit when on beach."
  unit_description_harpoonship: "Ranged anti-air water unit. Does half damage to enemies on land. Critical hit when in reef."
  unit_description_dragon: "Incredibly powerful air-to-ground unit. Critical hit when target is standing on a road."
  unit_description_knight: "[MELEE] Powerful, mobile ground unit. Critical hit when it attacks from a location six spaces away from where it starts."
  unit_description_wagon: "Capable of quickly transporting units that would otherwise travel by foot."
  unit_description_trebuchet: "Powerful long-range unit, unable to move and attack in the same turn. Critical hit at max range."
  unit_description_merman: "Amphibious infantry unit that can capture structures. Critical hit when in rivers or sea."
  unit_description_turtle: "[MELEE] Powerful naval unit, built to conquer the water. Critical hit when in deep sea."
  unit_description_witch: "Air-to-air unit. Critical hit when target is not adjacent to its own allied witch. Hex deals 10% damage to all unit types."
  unit_description_harpy: "Immensely mobile units, useful for crossing enemy lines. Critical hit when above a mountain."
  unit_description_balloon: "Aircraft able to transport footsoldiers and Dog units."
  unit_description_giant: "[MELEE] An immensely powerful unit. Critical hit when at or below 40% health."
  unit_description_ballista: "Ranged ground-to-air unit, unable to move and attack in the same turn. Critical hit at min range."
  unit_description_travelboat: "Boats able to transport all ground units across water. Can steal from buildings."  
  #backgrounds
  ui_cutscene_background_deck: "Ship Deck"
  ui_cutscene_background_outlaw_ship: "Outlaw Ship"
  ui_cutscene_background_outlaw_ship_right: "Outlaw Ship Mirrored"
  ui_cutscene_background_outlaw_cherry_ship: "Outlaw and Cherry Ship"
  ui_cutscene_background_outlaw_HQ: "Outlaw HQ"
  ui_cutscene_background_outlaw_HQ_intro: "Outlaw HQ Intro"
  ui_cutscene_background_tropical_beach: "Tropical Beach"
  ui_cutscene_background_tropical_beach_telescope: "Tropical Beach Telescope"
  ui_cutscene_background_sand_cave: "Sand Cave"
  ui_cutscene_background_forge: "Forge"
  ui_cutscene_background_grass_bridge_bg: "Grass Bridge BG"
  
  #cutscene sound effects
  ui_cutscene_sfx_wulfar_hug: "Wulfar and Vesper Hug"
  ui_cutscene_sfx_emeric_charged_attack: "Emeric Charged Attack"
  ui_cutscene_sfx_plip: "Plip"
  ui_cutscene_sfx_plop: "Plop"
  
  # CUTSCENE VISUAL EFFECTS
  ui_cutscene_vfx_wulfar_vesper_hug: "Wulfar and Vesper Hug"
  ui_cutscene_vfx_outlaw_HQ_banner: "Outlaw HQ Animated Banner"
  ui_cutscene_vfx_one_sec_fade_in: "One Sec Fade In"
  
  #Walk cycles
  ui_cutscene_walk_type_backwards_walk: "Backwards Walk"
  
  #HIGHLIGHTS
  location_highlight_tutorial_cross: "Tutorial Cross"
  
  # CUTSCENE PROPS
  ui_cutscene_prop_tavernfire: "Tavern Fire"
  ui_cutscene_prop_rays: "Light Rays"
  ui_cutscene_prop_outlawHQ_intro_groundlight: "Outlaw HQ Intro Groundlight"
  ui_cutscene_prop_outlawHQ_intro_windowlight: "Outlaw HQ Intro Windowlight"
  ui_cutscene_prop_sleeping_dog_prop: "Sleeping Dog"
  ui_cutscene_prop_outlaw_HQ_banner: "Outlaw HQ Animated Banner"
  ui_cutscene_prop_one_sec_fade_in: "One Sec Fade In"
  ui_cutscene_prop_cherrystone_building_background: "Cherrystone Building Background"
  ui_cutscene_prop_cherrystone_building_foreground: "Cherrystone Building Foreground"
  ui_cutscene_prop_telescope: "Telescope"
  ui_cutscene_prop_forge_flame: "Forge Flames"
  ui_cutscene_prop_large_table: "Large Table"
  ui_cutscene_prop_large_table_servings: "Large Table Servings"

  # MUSIC
  music_name_tavern_distant: "Distant Tavern"
  music_name_bar_ambience_distant: "Distant Tavern Ambience"
  
  # MAP HIGHLIGHT TYPES
  location_highlight_arrow_up: "Arrow up"
  ui_cutscene_emote_crown_surprise: "Crown Surprised"
  ui_cutscene_emote_crown_surprise_clean: "Crown Surprised Clean"
  ui_cutscene_emote_cushion_surprise_clean: "Cushion Surprised Clean"
  
  # CUTSCENE DUCHESS VOICE LINES
  ui_cutscene_shout_duchess_acoldwindblows: "\"A cold wind blows!\""
  ui_cutscene_shout_duchess_astormapproaches: "\"A storm approaches!\""
  ui_cutscene_shout_duchess_attack2: "Pained Grunt"
  ui_cutscene_shout_duchess_attack3: "Grunt of Exertion"
  ui_cutscene_shout_duchess_attack4: "Frustrated Grunt"
  ui_cutscene_shout_duchess_ihavefailed: "\"I have failed.\""
  ui_cutscene_shout_duchess_illmakethisquick: "\"I'll make this quick.\""
  ui_cutscene_shout_duchess_imnotheretoplay: "\"I am not here to play.\""
  ui_cutscene_shout_duchess_hit1: "Shocked Cry"
  ui_cutscene_shout_duchess_hit2: "Angry Grunt"
  ui_cutscene_shout_duchess_hit3: "Shocked Grunt"
  ui_cutscene_shout_duchess_powerofthetempest: "\"Power of the tempest!\""
  ui_cutscene_shout_duchess_theresnotimetowaste: "\"There's no time to...\""
  ui_cutscene_shout_duchess_thewindrises: "\"The wind rises!\""
  ui_cutscene_shout_duchess_absolutelynot: "\"Absolutely not.\""
  ui_cutscene_shout_duchess_agreed: "\"Agreed.\""
  ui_cutscene_shout_duchess_fallback: "\"Fall back!\""
  ui_cutscene_shout_duchess_farewell: "\"Farewell.\""
  ui_cutscene_shout_duchess_getoutofmysight: "\"Get out of my sight!\""
  ui_cutscene_shout_duchess_greetings: "\"Greetings.\""
  ui_cutscene_shout_duchess_hmph: "\"Hmph.\""
  ui_cutscene_shout_duchess_howtimeflies: "\"How time flies.\""
  ui_cutscene_shout_duchess_itireofyourpresence: "\"I tire of your presence.\""
  ui_cutscene_shout_duchess_koji1: "Angry \"Koji!\""
  ui_cutscene_shout_duchess_koji2: "Fearful \"Koji!\""
  ui_cutscene_shout_duchess_laugh1: "Laugh"
  ui_cutscene_shout_duchess_laugh2: "Chuckle"
  ui_cutscene_shout_duchess_no: "\"No.\""
  ui_cutscene_shout_duchess_noonethreatensmypeople: "\"No one threatens my people.\""
  ui_cutscene_shout_duchess_sigh: "Sigh"
  ui_cutscene_shout_duchess_standdown: "\"Stand down!\""
  ui_cutscene_shout_duchess_stopthis: "\"Stop this!\""
  ui_cutscene_shout_duchess_victoryshallbeswift: "\"Victory shall be swift.\""
  ui_cutscene_shout_duchess_weareoldfriends: "\"We are old friends.\""
  ui_cutscene_shout_duchess_westandtogether: "\"We stand together.\""
  ui_cutscene_shout_duchess_whatisthis1: "\"What is this?\""
  ui_cutscene_shout_duchess_yes: "\"Yes.\""
  ui_cutscene_shout_duchess_youfiend: "\"You fiend!\""
  ui_cutscene_shout_duchess_youhavemythanks: "\"You have my thanks.\""
  ui_cutscene_shout_duchess_youthinkthisisagame: "\"You think this is a game?\""

...