---

worldMaps:
- id: aurania
  name: world_map_aurania_name
  icon: ui/campaign/map_icon1.png
  size: [720, 520]
  spriteSheet: ragnarok_world
  images:
  - image: world/maps/aurania_v2/world_map.png
    layer: background
    pos: [0, 0]
  - image: world/maps/aurania_v2/world_map_pillars.png
    layer: ground_decorations
    pos: [0, 0]
  - image: world/maps/aurania_v2/world_map_water.png
    effect: water
    layer: background_tiles_water
    mask: world/maps/aurania_v2/world_map_water_ramp.png
    pos: [0, 0]
  - animation: world/maps/aurania_v2/windmill
    layer: ground_decorations
    pos: [200, 210]
  fishAnimations:
  - world/world_map_fish_size01
  - world/world_map_fish_size02
  - world/world_map_fish_size03
  fishes:
  - pos: [240, 125]
    radius: 20
  - pos: [335, 168]
    radius: 60
  - pos: [337, 350]
    radius: 25
  - pos: [375, 415]
    radius: 40
  - pos: [592, 468]
    radius: 40
  - pos: [670, 475]
    radius: 50
  - pos: [460, 90]
    radius: 25
  - pos: [565, 55]
    radius: 25
  - pos: [680, 60]
    radius: 60
  sound:
  - event: environmental/oceanAmbienceWorld
  - event: environmental/fieldAmbienceWorld
    sources:
    # Cherrystone
    - pos: [66, 105]
      refDistance: 30
      maxDistance: 300
    - pos: [78, 260]
      refDistance: 30
      maxDistance: 300
  - event: environmental/forestAmbienceWorld
    sources:
    # The Gloomwoods
    - pos: [100, 30]
      refDistance: 20
      maxDistance: 200
    - pos: [300, 20]
      refDistance: 20
      maxDistance: 200
  - event: environmental/tundraAmbienceWorld
    sources:
    # Felheim
    - pos: [40, 450]
      refDistance: 20
      maxDistance: 200
    - pos: [180, 450]
      refDistance: 25
      maxDistance: 250
    - pos: [380, 500]
      refDistance: 10
      maxDistance: 100
  - event: environmental/mountainAmbienceWorld
    sources:
    # Outlaw HQ
    - pos: [230, 320]
      refDistance: 15
      maxDistance: 100
  - event: environmental/swampAmbienceWorld
    sources:
    # The Swamp
    - pos: [440, 230]
      refDistance: 20
      maxDistance: 200
  - event: environmental/volcanoAmbienceWorld
    sources:
    # Volcanic Island
    - pos: [760, 540]
      refDistance: 30
      maxDistance: 300
  - event: environmental/riverAmbienceWorld
    sources:
    #River from Felheim through Cherrystone
    - pos: [60, 465]
      refDistance: 15
      maxDistance: 150
    - pos: [260, 450]
      refDistance: 15
      maxDistance: 150
    - pos: [230, 380]
      refDistance: 15
      maxDistance: 150
    # Gloomwoods Rivers
    - pos: [200, 50]
      refDistance: 15
      maxDistance: 150
    - pos: [250, 40]
      refDistance: 15
      maxDistance: 150
    - pos: [365, 20]
      refDistance: 15
      maxDistance: 150
...
