---

unitClasses:
  - id: crew
    name: structure_name_city
    aiPriority: 0
    cargoSpace: 1
    battleUnitCount: 1
    damageMultiplier: 1
    movement: sea_building
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    income: 100
    cost: 500
    regeneration: 10
    tags:
      - structure
    sightRange: 1

units:
  - class: crew
    faction: neutral
    name: structure_name_city
    mapAnimation: units/crew/crew
    smallPortrait: units/villager/cherrystone/portrait_villager_cherrystone_small.png
    mediumPortrait: units/villager/cherrystone/portrait_villager_cherrystone_medium.png
    grabPos: [14, 15]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/city/city_background_full
      farBackground: city_background_full_background_2
      nearBackground: city_background_full_background_1
      foreground: city_background_full_foreground
      keeperPosition: [78, 95]
      leftBannerOffset: [-6, 2]
      rightBannerOffset: [0, 2]

...