---

unitClasses:
  - id: gate_no_los_blocker
    name: structure_name_gate
    aiPriority: 3.0
    cargoSpace: 1
    battleUnitCount: 1
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    damageMultiplier: 0.5
    movement: indoor_building
    garrisonUnit: ""
    cost: 500
    tags:
      - structure
    sightRange: 1

units:
  - class: gate_no_los_blocker
    faction: neutral
    name: structure_name_gate
    mapAnimation: [structures/gate, structures/gate_2]
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/gate.png
    grabPos: [15, 12]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
      deathMap: strongholdDieRed
    structureImage:
      spriteSheet: backgrounds/gate/gate_background_full
      farBackground: gate_background_full_background_2
      nearBackground: gate_background_full_background_2
      foreground: gate_background_full_background_2
      keeperPosition: [54, 75]
      leftBannerOffset: [0, 0]
      rightBannerOffset: [0, 0]
    hasBattleScreen: false

...