---

unitClasses:
  - id: lumbermill
    name: structure_name_lumbermill
    aiPriority: 3.0
    cargoSpace: 1
    battleUnitCount: 1
    damageMultiplier: 1
    movement: land_building
    isStructure: true
    canReinforce: true
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: true
    garrisonUnit: garrison
    income: 0
    cost: 500
    regeneration: 10
    recruitTags: [type.ground.test]
    verbs:
      - cut_trees
    tags:
      - structure
    sightRange: 1

units:
  - class: lumbermill
    faction: neutral
    name: structure_name_lumbermill
    mapAnimation: [structures/lumbermill]
    mapLightSource:
      sprite: lights_large
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.8, 0.8]
      jitter:
        scale: 0.33
        frequency: 0.3
        frequencyVariance: 0.15
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/lumbermill.png
    grabPos: [14, 15]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/lumbermill/lumbermill
      farBackground: lumbermill_background_2
      nearBackground: lumbermill_background_1
      foreground: lumbermill_foreground
      keeperPosition: [70, 90]
      leftBannerOffset: [-15, 1]
      rightBannerOffset: [-9, 1]

...