---

unitClasses:
  - id: tavern
    name: structure_name_tavern
    classIconSpritesheet: ui_RagnarokMod
    aiPriority: 3.0
    verbs:
      - recruit
    battleUnitCount: 1
    isStructure: true
    canReinforce: true
    canBeReinforced: false
#    hostileNeutral: false
    damageMultiplier: 0
    movement: land_building
    garrisonUnit: ""
    recruitTags: [type.ground.light, type.ground.heavy]
    cost: 500
    tags:
      - structure
    sightRange: 1

units:
  - class: tavern
    faction: neutral
    name: structure_name_tavern
    mapAnimation: structures/tavern
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/gate.png
    grabPos: [15, 12]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
      deathMap: strongholdDieRed
    structureImage:
      spriteSheet: backgrounds/gate/gate_background_full
      farBackground: gate_background_full_background_2
      nearBackground: gate_background_full_background_2
      foreground: gate_background_full_background_2
      keeperPosition: [54, 75]
      leftBannerOffset: [0, 0]
      rightBannerOffset: [0, 0]
    hasBattleScreen: false

...