---

unitClasses:
  - id: tavern
    name: structure_name_tavern
    aiPriority: 3.0
    verbs:
      - recruit
    battleUnitCount: 1
    isStructure: true
    canReinforce: true
    canBeReinforced: false
    canBeCaptured: false
    hostileNeutral: false
    damageMultiplier: 0
    movement: land_building
    recruitTags: [type.ground.light, knight, airtrooper, type.sea.light, type.amphibious.light, type.ground.hideout]
    cost: 500
    tags:
      - structure
    sightRange: 1

units:
  - class: tavern
    faction: neutral
    name: structure_name_tavern
    mapAnimation: structures/tavern
    mapLightSource:
      sprite: lights_large
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.8, 0.8]
      jitter:
        scale: 0.33
        frequency: 0.3
        frequencyVariance: 0.15
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/tavern_2.png
    grabPos: [15, 12]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
      deathMap: strongholdDieRed
    structureImage:
      spriteSheet: backgrounds/gate/gate_background_full
      farBackground: gate_background_full_background_2
      nearBackground: gate_background_full_background_2
      foreground: gate_background_full_background_2
      keeperPosition: [54, 75]
      leftBannerOffset: [0, 0]
      rightBannerOffset: [0, 0]

...