---
unitClasses:
  - id: griffin_walking
    name: unit_class_name_griffin
    cost: 400
    resourceCost: 2
    movement: airphibious
    moveRange: 5
    damageMultiplier: 1.0
    aiPriority: 1.0
    ignoresObstacles: true
    verbs:
      - attack_AI
      - capture
      - capture_AI
      - load
      - rescue
      - hire
      - take_crown
    weapons:
      - id: airtrooperBeak
    tags:
      - airtrooper
      - type.air
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 4
    canSeeOverTerrain: false

units:
  - class: griffin_walking
    faction: outlaw
    name: unit_name_griffin_outlaw
    mapAnimation: units/griffin/pirates/map_griffin_pirates
    mapLightSource:
      sprite: lights_medium
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.75, 0.4]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/griffin/outlaws/battle_griffin_outlaws_2
    battleAnimationRiver: fx/river_overlay/battle_airtrooper_pirates_river
    smallPortrait: units/griffin/pirates/portrait_griffin_pirates_small.png
    mediumPortrait: units/griffin/pirates/portrait_griffin_pirates_medium.png
    mapSpeed: 5.0
    grabPos: [17, 5]
    attackTimingsHack: false
    sounds:
      attackMap: unitAttack
      attack: airtrooperAttack
      death: airtrooperDie
      deathMap: unitDie
      run: airtrooperEntry
      runMap: airtrooperMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: [0.72]
    emotes:
      idle: idle

...