---

weapons:
  - id: ballistaBolt
    rangeMin: 2
    rangeMax: 6
    canMoveAndAttack: false
    baseDamage:
      air: 1
      land: 1
      water: 1      
    tagDamage:
      witch: 0.95
      dragon: 0.85
      harpy: 1.3
      balloon: 1.1

      archer: 0.3
      soldier: 0.4
      villager: 0.5
      dog: 0.5
      spearman: 0.3
      wagon: 0.3                  
      mage: 0.4
      knight: 0.25
      ballista: 0.2
      trebuchet: 0.1
      giant: 0.1
      structure: 0.3
      commander: 0.10
      rifleman: 0.5
      thief: 0.4

      flagship: 0.05
      warship: 0.2
      harpoonship: 0.3
      turtle: 0.4
      travelboat: 0.25
      merman: 0.4

unitClasses:
  - id: ballista
    name: unit_class_name_ballista
    cost: 800
    movement: wheels
    moveRange: 6
    damageMultiplier: 1
    aiPriority: 1.6
    weapons:
      - id: ballistaBolt
    tags:
      - ballista
      - type.ground.heavy
      - wheels
    verbs:
      - rescue
      - load
      - pick_up_crown
      - throw_crown
      - healing_potion
      - hire
      - wait_ai
    battleUnitCount: 1
    passiveMultiplier: 1.5
    sightRange: 4
    deathVerbId: death

units:
  - class: ballista
    faction: outlaw
    name: unit_name_ballista_outlaws
    mapAnimation: units/ballista/outlaws/map_ballista_outlaws
    battleAnimation: units/ballista/outlaws/battle_ballista_outlaws
    smallPortrait: units/ballista/outlaws/portrait_ballista_outlaws_small.png
    mediumPortrait: units/ballista/outlaws/portrait_ballista_outlaws_medium.png
    mapSpeed: 4.0
    grabPos: [16, 17]
    attackOffset: [30, 0]
    battlePosOffset: [-2, 0]
    deathMoveMin: 0
    deathMoveMax: 0
    stayAfterDeath: true
    sounds:
      attackMap: unitAttack
      attack: ballistaAttack
      attackEffect: ballistaAttackEffect
      death: gateDie
      deathMap: unitDie
      run: ballistaEntry
      runMap: ballistaEntry
      hit: hitWood
      hitMap: hitWood
    attacks:
      - id: primary
        ranged: true
        hitSpark: fx/bs_stab_attack
        hitDelay: 1.6
        effect: fx/bs_ballista_cherrystone_attack
        postAttackAnimationSequence: post_attack_idle
        postAttackHitSequence: post_attack_hit
        postAttackDeathSequence: post_attack_death
        attacksFlying: true
        effectDelay: 1.3
      - id: secondary
        ranged: true
        hitSpark: fx/bs_stab_attack
        hitDelay: 1.6
        effect: fx/bs_ballista_2_cherrystone_attack
        postAttackAnimationSequence: post_attack_idle
        postAttackHitSequence: post_attack_hit
        postAttackDeathSequence: post_attack_death
        effectDelay: 1.3
...
