---
weapons:
  - id: ballistaBolt
    rangeMin: 2
    rangeMax: 6
    canMoveAndAttack: false
    baseDamage:
      air: 1
      land: 1
      water: 1
      buildings: 1      

unitClasses:
  - id: ballista
    name: unit_class_name_ballista
    cost: 800
    movement: wheels
    moveRange: 6
    damageMultiplier: 1
    aiPriority: 1.6
    weapons:
      - id: ballistaBolt
    tags:
      - ballista
      - type.ground.heavy
    verbs:
      - load
      - rescue
      - attack_AI
      - hire
      - take_crown
    battleUnitCount: 1
    passiveMultiplier: 1.5
    sightRange: 4
    
units:
  - class: ballista
    faction: outlaw
    name: unit_name_ballista_outlaw
    mapAnimation: units/ballista/outlaw/map_ballista_outlaw
    mapLightSource:
      sprite: lights_medium
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_large
      scale: [0.95, 0.55]
      jitter:
        scale: 0.5
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/ballista/outlaw/battle_ballista_outlaw
    smallPortrait: units/ballista/outlaw/portrait_ballista_outlaw_small.png
    mediumPortrait: units/ballista/outlaw/portrait_ballista_outlaw_medium.png
    mapSpeed: 4.0
    grabPos: [16, 17]
    attackOffset: [30, 0]
    battlePosOffset: [-2, 0]
    deathMoveMin: 0
    deathMoveMax: 0
    stayAfterDeath: true
    sounds:
      attackMap: unitAttack
      attack: ballistaAttack
      attackEffect: ballistaAttackEffect
      death: gateDie
      deathMap: unitDie
      run: ballistaEntry
      runMap: ballistaEntry
      hit: hitWood
      hitMap: hitWood
    attacks:
      - id: primary
        ranged: true
        hitSpark: fx/bs_stab_attack
        hitDelay: 1.6
        effect: fx/bs_ballista_cherrystone_attack
        postAttackAnimationSequence: post_attack_idle
        postAttackHitSequence: post_attack_hit
        postAttackDeathSequence: post_attack_death
        attacksFlying: true
        effectDelay: 1.3
      - id: secondary
        ranged: true
        hitSpark: fx/bs_stab_attack
        hitDelay: 1.6
        effect: fx/bs_ballista_2_cherrystone_attack
        postAttackAnimationSequence: post_attack_idle
        postAttackHitSequence: post_attack_hit
        postAttackDeathSequence: post_attack_death
        effectDelay: 1.3
    emotes:
      idle: idle

...