---

weapons:
  - id: ballistaBolt
    rangeMin: 2
    rangeMax: 6
    canMoveAndAttack: false
    baseDamage:
      air: 1
      land: 1
      water: 1      
    tagDamage:
      witch: 1
      dragon: 0.9
      harpy: 1.35
      balloon: 1.15

      archer: 0.35
      soldier: 0.45
      villager: 0.45
      dog: 0.55
      spearman: 0.35
      wagon: 0.35              
      mage: 0.45
      knight: 0.3
      ballista: 0.25
      trebuchet: 0.15
      giant: 0.15
      structure: 0.35
      commander: 0.15
      rifleman: 0.55
      thief: 0.45

      flagship: 0.15
      pirate_ship: 0.35
      warship: 0.25
      harpoonship: 0.35
      turtle: 0.45
      travelboat: 0.3
      merman: 0.45

unitClasses:
  - id: ballista
    name: unit_class_name_ballista
    cost: 800
    movement: wheels
    moveRange: 6
    damageMultiplier: 1
    aiPriority: 1.6
    weapons:
      - id: ballistaBolt
    tags:
      - ballista
      - type.ground.heavy
    verbs:
      - rescue
      - load
      - pick_up_crown
      - throw_crown
      - healing_potion
    battleUnitCount: 1
    passiveMultiplier: 1.5
    sightRange: 4
...
