---

unitClasses:
  - id: crew
    name: unit_class_name_area_heal
    movement: walking
    moveRange: 0
    damageMultiplier: 0
    aiPriority: 0
    battleUnitCount: 1
    passiveMultiplier: 1.25
    sightRange: 200
    canSeeOverTerrain: true
    classIcon: unit_icons_summon
    hasTurn: false
    isRecruitable: false
    isSpawnable: true
    hasDeathAnimation: false
    appearsInLists: true
    tags:
      - summon


units:
  - class: crew
    faction: outlaw
    name: unit_name_villager_cherrystone
    mapAnimation: units/villager/cherrystone/map_villager_cherrystone
    battleAnimation: units/villager/cherrystone/battle_villager_cherrystone
    battleAnimationRiver: fx/river_overlay/battle_villager_river
    smallPortrait: units/villager/cherrystone/portrait_villager_cherrystone_small.png
    mediumPortrait: units/villager/cherrystone/portrait_villager_cherrystone_medium.png
    mapSpeed: 4.0
    grabPos: [13, 14]
    runsIn: false
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      death: emeric/emericCrystalDie
      deathMap: unitDie
      deathMapNoBattle: emeric/emericCrystalDie
      hit: hitStone
      hitMap: hitStone

...
