---

weapons:
  - id: caesarBite
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.3
      soldier: 1.15
      villager: 1.25
      spearman: 0.75
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.65
      ballista: 0.7
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      rifleman: 1.05
      thief: 0.95
      
      pirate_ship: 0.6
      warship: 0.55
      harpoonship: 0.6
      turtle: 0.55
      travelboat: 0.45
      merman: 0.95


unitClasses:
  - id: commander_duke
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: caesarBite
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    sightRange: 4
    isCommander: true
    grooveId: groove_alert_area


units:
  - class: commander_duke
    faction: cherrystone
    name: character_duke_name
    mapAnimation: units/commanders/duchess/map_duchess
    battleAnimation: units/commanders/duchess/battle_duchess
    battleAnimationRiver: fx/river_overlay/battle_caesar_river
    smallPortrait: units/commanders/duchess/portrait_duchess_small.png
    mediumPortrait: units/commanders/duchess/portrait_duchess_medium.png
    menuIdleSequence: capture_idle
    mapSpeed: 4.0
    skinColour: typeV
    grabPos: [27, 27]
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      attackMap: unitAttack
      attack: duchess/duchessAttack
      counter: duchess/duchessCounterAttack
      captureShout: duchess/duchessCapture
      death: duchess/duchessDie
      deathMap: duchess/duchessDieGhost
      deathMapNoBattle: duchess/duchessDieNoBattle
      run: infantryHeavyEntry
      runMap: infantryHeavyMapEntry
      firstHit: duchess/duchessHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: duchess/duchessGrooveIntro
    attacks:
      - id: primary
        attackAnimationSequence: counter
        hitSpark: fx/bs_stab_attack
        hitDelay: [1.0, 1.1]
        samePanel: true
        attackSound: counter
      - id: secondary
        attackAnimationSequence: [attack]
        hitSpark: fx/bs_stab_attack
        effect: fx/bs_duchess_attack
        effectDelay: 1.4
        hitDelay: 1.4
        ranged: true
        attackSound: [attack]
    cutscenePreIdle: ""
    cutsceneIdle: capture_idle
    cutsceneHit: hit_foot
    emotes:
      idle: capture_idle
      surprise: emote_surprise
      positive: emote_positive
      negative: emote_negative
      laugh: emote_laugh
      sniff: emote_sniff
      hypno: emote_hypno
      howl: emote_howl
      unhappy: emote_unhappy
      darkcaesar: emote_darkcaesar
      dance: emote_dance
      sleep: emote_sleep
    shouts:
      duchess_aurevoir: duchess/duchessShoutAuRevoir
      duchess_beautifullyappointed: duchess/duchessShoutBeautifullyAppointed
      duchess_bonnechance: duchess/duchessShoutBonneChance
      duchess_caesar: duchess/duchessShoutCaesar
      duchess_canefaitrien: duchess/duchessShoutCaNeFaitRien
      duchess_cestlaguerre: duchess/duchessShoutCestLaGuerre
      duchess_commanderryota: duchess/duchessShoutCommanderRyota
      duchess_dog: duchess/duchessShoutDog
      duchess_empresstenri: duchess/duchessShoutEmpressTenri
      duchess_enid: duchess/duchessShoutEnid
      duchess_errol: duchess/duchessShoutErrol
      duchess_errorandawful: duchess/duchessShoutErrorAndAwful
      duchess_felllord: duchess/duchessShoutFellLord
      duchess_floran: duchess/duchessShoutFloran
      duchess_flymypretty: duchess/duchessShoutFlyMyPretty
      duchess_greenfingerzawan: duchess/duchessShoutGreenfingerZawan
      duchess_hardlysurprising: duchess/duchessShoutHardlySurprising
      duchess_hellowulfar: duchess/duchessShoutHelloWulfar
      duchess_hit1: duchess/duchessShoutHit1
      duchess_hit2: duchess/duchessShoutHit2
      duchess_hit3: duchess/duchessShoutHit3
      duchess_hit4: duchess/duchessShoutHit4
      duchess_hit5: duchess/duchessShoutHit5
      duchess_hm: duchess/duchessShoutHm
      duchess_hmm1: duchess/duchessShoutHmm1
      duchess_hmm2: duchess/duchessShoutHmm2
      duchess_hmm3: duchess/duchessShoutHmm3
      duchess_hmph: duchess/duchessShoutHmph
      duchess_howdareyou: duchess/duchessShoutHowDareYou
      duchess_howdelightful: duchess/duchessShoutHowDelightful
      duchess_huh: duchess/duchessShoutHuh
      duchess_icastalongshadow: duchess/duchessShoutICastALongShadow
      duchess_illjustbeonmywaynow: duchess/duchessShoutIllJustBeOnMyWayNow
      duchess_illwinthisgame: duchess/duchessShoutIllWinThisGame
      duchess_introduction: duchess/duchessShoutIntroduction
      duchess_itsduchessdarling: duchess/duchessShoutItsduchessDarling
      duchess_iwantriches: duchess/duchessShoutIWantRiches
      duchess_justajoke: duchess/duchessShoutJustAJoke
      duchess_justhereforthegold: duchess/duchessShoutJustHereForTheGold
      duchess_justwhatineeded: duchess/duchessShoutJustWhatINeeded
      duchess_laugh1: duchess/duchessShoutLaugh1
      duchess_laugh2: duchess/duchessShoutLaugh2
      duchess_laugh3: duchess/duchessShoutLaugh3
      duchess_laugh4: duchess/duchessShoutLaugh4
      duchess_laugh5: duchess/duchessShoutLaugh5
      duchess_nestcepas: duchess/duchessShoutNestcePas
      duchess_no1: duchess/duchessShoutNo1
      duchess_no2: duchess/duchessShoutNo2
      duchess_noangry: duchess/duchessShoutNoAngry
      duchess_noupset: duchess/duchessShoutNoUpset
      duchess_nosmokewithoutfire: duchess/duchessShoutNoSmokeWithoutFire
      duchess_nuru: duchess/duchessShoutNuru
      duchess_oopsie: duchess/duchessShoutOopsie
      duchess_orla: duchess/duchessShoutOrla
      duchess_pluscachange: duchess/duchessShoutPlusCaChange
      duchess_princekoji: duchess/duchessShoutPrinceKoji
      duchess_queenmercia: duchess/duchessShoutQueenMercia
      duchess_queldommage: duchess/duchessShoutQuelDommage
      duchess_quitethecoupdetheatre: duchess/duchessShoutQuiteTheCoupDeTheatre
      duchess_ragna: duchess/duchessShoutRagna
      duchess_sedge: duchess/duchessShoutSedge
      duchess_shesclearlyamoron: duchess/duchessShoutShesClearlyAMoron
      duchess_shh: duchess/duchessShoutShh
      duchess_shush: duchess/duchessShoutShush
      duchess_sicem: duchess/duchessShoutSicEm
      duchess_sigh: duchess/duchessShoutSigh
      duchess_sighannoyed: duchess/duchessShoutSighAnnoyed
      duchess_sigrid: duchess/duchessShoutSigrid
      duchess_siremeric: duchess/duchessShoutSirEmeric
      duchess_smokeandshadows: duchess/duchessShoutSmokeAndShadows
      duchess_sosad: duchess/duchessShoutSoSad
      duchess_thankyou: duchess/duchessShoutThankYou
      duchess_theloot: duchess/duchessShoutTheLoot
      duchess_thishasbeenentertaining: duchess/duchessShoutThisHasBeenEntertaining
      duchess_turnthatfrown: duchess/duchessShoutTurnThatFrown
      duchess_valder: duchess/duchessShoutValder
      duchess_vampire: duchess/duchessShoutVampire
      duchess_watchthis: duchess/duchessShoutWatchThis
      duchess_welcometothedarkness: duchess/duchessShoutWelcomeToTheDarkness
      duchess_welldoneme: duchess/duchessShoutWellDoneMe
      duchess_what: duchess/duchessShoutWhat
      duchess_whatsalittleturpitude: duchess/duchessShoutWhatsALittleTurpitude
      duchess_wonderful: duchess/duchessShoutWonderful
      duchess_wulfar: duchess/duchessShoutWulfar
      duchess_yes1: duchess/duchessShoutYes1
      duchess_yes2: duchess/duchessShoutYes2
      duchess_youwillchoke: duchess/duchessShoutYouWillChoke
...
