---

weapons:
  - id: caesarBite
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.3
      soldier: 1.15
      villager: 1.25
      spearman: 0.75
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.65
      ballista: 0.7
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      rifleman: 1.05
      thief: 0.95
      
      pirate_ship: 0.6
      warship: 0.55
      harpoonship: 0.6
      turtle: 0.55
      travelboat: 0.45
      merman: 0.95


unitClasses:
  - id: commander_duchess
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: caesarBite
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    sightRange: 4
    isCommander: true
    grooveId: groove_morale_boost


units:
  - class: commander_duchess
    faction: cherrystone
    name: character_duchess_name
    mapAnimation: units/commanders/duchess/map_duchess
    battleAnimation: units/commanders/duchess/battle_duchess
    battleAnimationRiver: fx/river_overlay/battle_caesar_river
    smallPortrait: units/commanders/duchess/portrait_duchess_small.png
    mediumPortrait: units/commanders/duchess/portrait_duchess_medium.png
    mapSpeed: 4.0
    skinColour: typeV
    grabPos: [47, 48]
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      attackMap: unitAttack
      attack: duchess/duchessAttack
      counter: duchess/duchessCounterAttack
      attackCommanderShout: duchess/duchessCommanderKillShout
      captureShout: duchess/duchessCapture
      death: duchess/duchessDie
      deathMap: duchess/duchessDieGhost
      deathMapNoBattle: duchess/duchessDieNoBattle
      run: infantryHeavyEntry
      runMap: infantryHeavyMapEntry
      firstHit: duchess/duchessHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: duchess/duchessGrooveIntro
    attacks:
      - id: primary
        attackAnimationSequence: counter
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.42
        samePanel: true
        attackSound: counter
      - id: secondary
        attackAnimationSequence: [attack]
        hitSpark: fx/bs_stab_attack
        effect: fx/bs_duchess_attack
        effectDelay: 1.4
        hitDelay: 1.4
        ranged: true
        attackSound: [attack]
    emotes:
      idle: idle
      surprise: emote_surprise
      positive: emote_positive
      negative: emote_negative
      laugh: emote_laugh
      sniff: emote_sniff
      hypno: emote_hypno
      howl: emote_howl
      unhappy: emote_unhappy
      darkcaesar: emote_darkcaesar
      dance: emote_dance
      sleep: emote_sleep
    shouts:
      duchess_acoldwindblows: duchess/duchessShoutAColdWindBlows
      duchess_astormapproaches: duchess/duchessShoutAStormApproaches
      duchess_attack1: duchess/duchessShoutAttack1
      duchess_attack2: duchess/duchessShoutAttack2
      duchess_attack3: duchess/duchessShoutAttack3
      duchess_attack4: duchess/duchessShoutAttack4
      duchess_ihavefailed: duchess/duchessShoutIHaveFailed
      duchess_imnotheretoplay: duchess/duchessShoutImNotHereToPlay
      duchess_hit1: duchess/duchessShoutHit1
      duchess_hit2: duchess/duchessShoutHit2
      duchess_hit3: duchess/duchessShoutHit3
      duchess_powerofthetempest: duchess/duchessShoutPowerOfTheTempest
      duchess_theresnotimetowaste: duchess/duchessShoutTheresNoTimeToWaste
      duchess_thewindrises: duchess/duchessShoutTheWindRises
      duchess_illmakethisquick: duchess/duchessShoutIllMakeThisQuick
      duchess_absolutelynot: duchess/duchessShoutAbsolutelyNot
      duchess_agreed: duchess/duchessShoutAgreed
      duchess_fallback: duchess/duchessShoutFallBack
      duchess_farewell: duchess/duchessShoutFarewell
      duchess_getoutofmysight: duchess/duchessShoutGetOutOfMySight
      duchess_greetings: duchess/duchessShoutGreetings
      duchess_hmph: duchess/duchessShoutHmph
      duchess_howtimeflies: duchess/duchessShoutHowTimeFlies
      duchess_itireofyourpresence: duchess/duchessShoutITireOfYourPresence
      duchess_koji1: duchess/duchessShoutKoji1
      duchess_koji2: duchess/duchessShoutKoji2
      duchess_laugh1: duchess/duchessShoutLaugh1
      duchess_laugh2: duchess/duchessShoutLaugh2
      duchess_no: duchess/duchessShoutNo
      duchess_noonethreatensmypeople: duchess/duchessShoutNoOneThreatensMyPeople
      duchess_sigh: duchess/duchessShoutSigh
      duchess_standdown: duchess/duchessShoutStandDown
      duchess_stopthis: duchess/duchessShoutStopThis
      duchess_victoryshallbeswift: duchess/duchessShoutVictoryShallBeSwift
      duchess_weareoldfriends: duchess/duchessShoutWeAreOldFriends
      duchess_westandtogether: duchess/duchessShoutWeStandTogether
      duchess_whatisthis1: duchess/duchessShoutWhatIsThis1
      duchess_whatisthis2: duchess/duchessShoutWhatIsThis2
      duchess_yes: duchess/duchessShoutYes
      duchess_youfiend: duchess/duchessShoutYouFiend
      duchess_youhavemythanks: duchess/duchessShoutYouHaveMyThanks
      duchess_youthinkthisisagame: duchess/duchessShoutYouThinkThisIsAGame
...
