---

weapons:
  - id: flagship_cannon
    rangeMin: 1
    rangeMax: 2
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.35
      soldier: 1.2
      villager: 1
      spearman: 0.8
      dog: 1.2
      wagon: 0.75
      knight: 0.6
      trebuchet: 0.7
      ballista: 0.75
      dragon: 0.35
      mage: 0.85
      giant: 0.45
      structure: 0.75
      balloon: 0.6
      harpy: 0.95
      witch: 0.75
      dragon: 0.4
      commander: 0.45
      rifleman: 1.1
      thief: 1.0
      
      warship: 0.6
      harpoonship: 0.65
      turtle: 0.6
      travelboat: 0.5
      merman: 1.0
      flagship: 0.45
      pirate_ship: 0.65

unitClasses:
  - id: commander_flagship_wulfar
    name: unit_class_name_flagship_wulfar
    cost: 500
    movement: sailing
    moveRange: 6
    aiPriority: 4.0
    weapons:
      - id: flagship_cannon
    verbs:
      - rescue
      - pirate_claim
    cargoSpace: 2
    tags:
      - flagship
      - type.sea
    battleUnitCount: 1
    passiveMultiplier: 1
    sightRange: 5
    regeneration: 5
    isCommander: true
    grooveId: groove_broadside
    isHiddenInCutsceneEditor: true

units:
  - class: commander_flagship_wulfar
    faction: outlaw
    name: unit_name_flagship_wulfar
    mapAnimation: units/flagship/map_flagship
    battleAnimation: units/flagship/battle_flagship_wulfar
    smallPortrait: units/warship/outlaw/portrait_warship_outlaw_small.png
    mediumPortrait: units/warship/outlaw/portrait_warship_outlaw_medium.png
    mapSpeed: 9.0
    skinColour: typeII
    grabPos: [10, 9]
    deathMoveMin: 80
    deathMoveMax: 80
    sounds:
      attackMap: unitAttack
      attack: flagshipWulfarAttack
      attackEffect: warshipAttackEffect
      death: shipDie
      deathMap: unitDie
      run: waterBoatEntry
      runMap: waterBoatEntry
      hit: hitWood
      hitMap: hitWood
    attacks:
      - id: primary
        hitDelay: 2.0
        hitSpark: fx/bs_stab_attack
        ranged: true
        effect: fx/bs_warship_attack
        effectDelay: 1.8
        hitDelay: [2.0, 2.3, 2.6]
