---

unitClasses:
  - id: crew
    name: unit_class_name_crew
    cost: 0
    movement: sea_building
    moveRange: 0
    damageMultiplier: 0
    classIconSpritesheet: ui_RagnarokMod
    aiPriority: 0
    battleUnitCount: 1
    isRecruitable: false
    sightRange: 0


units:
  - class: crew
    faction: cherrystone
    name: unit_name_crew
    mapAnimation: units/crew/map_crew
    battleAnimation: units/crew/battle_crew
    battleAnimationRiver: fx/river_overlay/battle_thief_river
    smallPortrait: units/crew/portrait_crew_small.png
    mediumPortrait: units/crew/portrait_crew_medium.png
    mapSpeed: 4.0
    grabPos: [13, 14]
    deathMoveMin: 0
    deathMoveMax: 0
    stayAfterDeath: true
    sounds:
      death: thiefLoadedDieRed
      deathMap: unitDie
      run: thiefLoadedMapEntry
      runMap: thiefLoadedMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
...
