
---

weapons:
  - id: bite
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      water: 1
      land: 1
    tagDamage:
      archer: 0.8
      soldier: 0.8
      villager: 0.8
      spearman: 0.5
      dog: 0.7
      wagon: 0.35
      knight: 0.15
      trebuchet: 0.5
      ballista: 0.55
      giant: 0.1
      dragon: 100 #goodboy
      merman: 0.8
      mage: 0.6
      structure: 0.25
      commander: 0.2
      rifleman: 1.15
      thief: 0.9
      
      warship: 0.1
      harpoonship: 0.15
      turtle: 0.25
      travelboat: 0.15
      pirate_ship: 0.15
      flagship: 0.1
      
unitClasses:
  - id: dog
    name: unit_class_name_dog
    cost: 150
    movement: walking
    moveRange: 5
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: bite
    verbs:
      - rescue
      - load
      - pick_up_crown
      - throw_crown
      - healing_potion
    tags:
      - dog
      - type.ground.light
      - animal
      - type.scout
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 5
    scout: true
    runsAway: true
    deathVerbId: death_drop_crown
    
units:
  - class: dog
    faction: outlaw
    name: unit_name_dog_outlaws
    mapAnimation: units/dog/outlaws/map_dog_outlaws
    battleAnimation: units/dog/outlaws/battle_dog_outlaws
    battleAnimationRiver: fx/river_overlay/battle_dog_cherrystone_river
    smallPortrait: units/dog/outlaws/portrait_dog_outlaws_small.png
    mediumPortrait: units/dog/outlaws/portrait_dog_outlaws_medium.png
    mapSpeed: 5.0
    grabPos: [15, 23]
    sounds:
      attackMap: unitAttack
      attack: dogAttack
      attackShout: dogPreAttack
      death: dogDie
      deathMap: unitDie
      run: dogEntry
      runMap: dogMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.3
    shouts:      
      dog_shout1: dogShoutGrowl
      caesar_bark1: dogShoutBark

...
