---

unitClasses:
  - id: flare
    name: unit_class_name_flare
    cost: 150
    damageMultiplier: 2
    movement: flying
    moveRange: 2
    aiPriority: 0.1
    weapons: []
    tags:
      - summon
      - type.air
      - type.scout
    battleUnitCount: 1
    canAttack: false
    canSeeOverTerrain: true
    regeneration: -35
    classIcon: unit_icons_summon
    scout: true
    sightRange: 6


units:
  - class: flare
    faction: cherrystone
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/balloon/cherrystone/battle_balloon_cherrystone
    smallPortrait: units/balloon/cherrystone/portrait_balloon_cherrystone_small.png
    mediumPortrait: units/balloon/cherrystone/portrait_balloon_cherrystone_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood

  - class: flare
    faction: felheim
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/balloon/felheim/battle_balloon_felheim
    smallPortrait: units/balloon/felheim/portrait_balloon_felheim_small.png
    mediumPortrait: units/balloon/felheim/portrait_balloon_felheim_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDieBlue
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood

  - class: balloon
    faction: heavensong
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/balloon/heavensong/battle_balloon_heavensong
    smallPortrait: units/balloon/heavensong/portrait_balloon_heavensong_small.png
    mediumPortrait: units/balloon/heavensong/portrait_balloon_heavensong_medium.png
    mapSpeed: 3.0
    grabPos: [23, 4]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood


  - class: flare
    faction: floran
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/balloon/floran/battle_balloon_floran
    smallPortrait: units/balloon/floran/portrait_balloon_floran_small.png
    mediumPortrait: units/balloon/floran/portrait_balloon_floran_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood

  - class: flare
    faction: outlaw
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/flare/battle_flare
    smallPortrait: units/flare/portrait_flare_small.png
    mediumPortrait: units/flare/portrait_flare_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood
...
