---

unitClasses:
  - id: flare
    name: unit_class_name_flare
    cost: 150
    damageMultiplier: 2
    movement: hovering
    moveRange: 2
    aiPriority: 0.1
    weapons: []
    verbs:
      - wait_ai
    tags:
      - summon
      - type.air
      - type.scout
      - flying
    battleUnitCount: 1
    canAttack: false
    canSeeOverTerrain: true
    regeneration: -35
    classIcon: unit_icons_summon
    scout: true
    sightRange: 5
    deathVerbId: death


units:
  - class: flare
    faction: cherrystone
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/flare/battle_flare
    smallPortrait: units/flare/portrait_flare_small.png
    mediumPortrait: units/flare/portrait_flare_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood

  - class: flare
    faction: felheim
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/flare/battle_flare
    smallPortrait: units/flare/portrait_flare_small.png
    mediumPortrait: units/flare/portrait_flare_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDieBlue
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood

  - class: flare
    faction: heavensong
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/flare/battle_flare
    smallPortrait: units/flare/portrait_flare_small.png
    mediumPortrait: units/flare/portrait_flare_medium.png
    mapSpeed: 3.0
    grabPos: [23, 4]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood


  - class: flare
    faction: floran
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/flare/battle_flare
    smallPortrait: units/flare/portrait_flare_small.png
    mediumPortrait: units/flare/portrait_flare_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood

  - class: flare
    faction: outlaw
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/flare/battle_flare
    smallPortrait: units/flare/portrait_flare_small.png
    mediumPortrait: units/flare/portrait_flare_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood
...
