---

unitClasses:
  - id: flare
    name: unit_class_name_flare
    cost: 150
    damageMultiplier: 2
    movement: hovering
    moveRange: 2
    aiPriority: 0.1
    weapons: []
    tags:
      - summon
      - type.air
      - type.scout
    battleUnitCount: 1
    canAttack: false
    canSeeOverTerrain: true
    treatAsNeutralObstacle: true
    canBeReinforced: false
    regeneration: -35
    classIcon: unit_icons_summon
    scout: true
    isRecruitable: true
    sightRange: 4
    deathVerbId: death


units:
  - class: flare
    faction: cherrystone
    mapLightSource:
      sprite: lights_medium
      scale: [2.0, 2.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_air
      scale: [1.1, 1.1]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    name: unit_name_flare
    mapAnimation: units/flare/map_flare
    battleAnimation: units/flare/battle_flare
    smallPortrait: units/flare/portrait_flare_small.png
    mediumPortrait: units/flare/portrait_flare_medium.png
    mapSpeed: 3.0
    grabPos: [22, 5]
    sounds:
      death: balloonDie
      deathMap: flareDie
      run: balloonEntry
      runMap: balloonEntryMap
      hit: hitWood
      hitMap: hitWood
...
