---

weapons:
  - id: frog_tongue
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
      buildings: 1

unitClasses:
  - id: frog
    name: unit_class_name_frog
    cost: 600
    resourceCost: 2
    movement: amphibious
    moveRange: 6
    damageMultiplier: 1
    uiEffectivenessMultiplier: 2
    aiPriority: 1.0
    weapons:
      - id: frog_tongue
    verbs:
      - load
      - pull
      - rescue
      - attack_AI
      - hire
      - take_crown
    tags:
      - frog
      - type.amphibious.light
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 4

units:
  - class: frog
    faction: outlaw
    name: unit_name_frog_outlaw
    mapAnimation: units/frog/outlaw/map_frog_outlaw_2
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    mapAnimationWater: units/frog/outlaw/map_frog_swim_outlaw_2
    battleAnimation: units/frog/outlaw/battle_frog_outlaw_2
    battleAnimationRiver: fx/river_overlay/battle_frog_river
    battleAnimationWater: units/frog/outlaw/battle_frog_swim_outlaw_2
    smallPortrait: units/frog/outlaw/portrait_frog_outlaw_small_2.png
    mediumPortrait: units/frog/outlaw/portrait_frog_outlaw_medium_2.png
    mapSpeed: 7.0
    grabPos: [26, 76]
    attackRunTimeMin: 3.5
    attackRunTimeMax: 3.5
    attackTimingsHack: false
    emotes:
      idle: idle
      croak: emote_croak
    sounds:
      attackMap: unitAttack
      attack: frogAttack
      death: frogDie
      deathMap: unitDie
      run: frogMapEntry
      runMap: frogMapEntry
      runWater: frogMapWaterEntry
      runMapWater: frogMapWaterEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.6

  - class: frog
    faction: cherrystone
    name: unit_name_frog_cherrystone
    mapAnimation: units/frog/cherrystone/map_frog_cherrystone
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    mapAnimationWater: units/frog/cherrystone/map_frog_swim_cherrystone
    battleAnimation: units/frog/cherrystone/battle_frog_cherrystone
    battleAnimationRiver: fx/river_overlay/battle_frog_river
    battleAnimationWater: units/frog/cherrystone/battle_frog_swim_cherrystone
    smallPortrait: units/frog/cherrystone/portrait_frog_cherrystone_small.png
    mediumPortrait: units/frog/cherrystone/portrait_frog_cherrystone_medium.png
    mapSpeed: 7.0
    grabPos: [14, 75]
    attackTimingsHack: false
    emotes:
      idle: idle
    sounds:
      attackMap: unitAttack
      attack: frogAttack
      death: frogDie
      deathMap: unitDie
      run: frogMapEntry
      runMap: frogMapEntry
      runWater: frogMapWaterEntry
      runMapWater: frogMapWaterEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.5

  - class: frog
    faction: felheim
    name: unit_name_frog_felheim
    mapAnimation: units/frog/felheim/map_frog_felheim
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    mapAnimationWater: units/frog/felheim/map_frog_swim_felheim
    battleAnimation: units/frog/felheim/battle_frog_felheim
    battleAnimationRiver: fx/river_overlay/battle_frog_river
    battleAnimationWater: units/frog/felheim/battle_frog_swim_felheim
    smallPortrait: units/frog/felheim/portrait_frog_felheim_small.png
    mediumPortrait: units/frog/felheim/portrait_frog_felheim_medium.png
    mapSpeed: 7.0
    grabPos: [14, 75]
    attackTimingsHack: false
    sounds:
      attackMap: unitAttack
      attack: frogAttack
      death: frogDieBlue
      deathMap: unitDie
      run: frogMapEntry
      runMap: frogMapEntry
      runWater: frogMapWaterEntry
      runMapWater: frogMapWaterEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.5
    emotes:
      idle: idle
      frogpose1: emote_frogpose1
      frogpose2: emote_frogpose2    

  - class: frog
    faction: heavensong
    name: unit_name_frog_heavensong
    mapAnimation: units/frog/heavensong/map_frog_heavensong
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    mapAnimationWater: units/frog/heavensong/map_frog_swim_heavensong
    battleAnimation: units/frog/heavensong/battle_frog_heavensong
    battleAnimationRiver: fx/river_overlay/battle_frog_river
    battleAnimationWater: units/frog/heavensong/battle_frog_swim_heavensong
    smallPortrait: units/frog/heavensong/portrait_frog_heavensong_small.png
    mediumPortrait: units/frog/heavensong/portrait_frog_heavensong_medium.png
    mapSpeed: 7.0
    grabPos: [14, 75]
    attackTimingsHack: false
    emotes:
      idle: idle
    sounds:
      attackMap: unitAttack
      attack: frogAttack
      death: frogDieYellow
      deathMap: unitDie
      run: frogMapEntryYellow
      runMap: frogMapEntryYellow
      runWater: frogMapWaterEntryYellow
      runMapWater: frogMapWaterEntryYellow
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.5

  - class: frog
    faction: floran
    name: unit_name_frog_floran
    mapAnimation: units/frog/floran/map_frog_floran
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    mapAnimationWater: units/frog/floran/map_frog_swim_floran
    battleAnimation: units/frog/floran/battle_frog_floran
    battleAnimationRiver: fx/river_overlay/battle_frog_river
    battleAnimationWater: units/frog/floran/battle_frog_swim_floran
    smallPortrait: units/frog/floran/portrait_frog_floran_small.png
    mediumPortrait: units/frog/floran/portrait_frog_floran_medium.png
    mapSpeed: 7.0
    grabPos: [14, 75]
    attackTimingsHack: false
    emotes:
      idle: idle
    sounds:
      attackMap: unitAttack
      attack: frogAttack
      death: frogDie
      deathMap: unitDie
      run: frogMapEntry
      runMap: frogMapEntry
      runWater: frogMapWaterEntry
      runMapWater: frogMapWaterEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.5

  - class: frog
    faction: faahri
    name: unit_name_frog_faahri
    mapAnimation: units/frog/faahri/map_frog_faahri
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    mapAnimationWater: units/frog/faahri/map_frog_swim_faahri
    battleAnimation: units/frog/faahri/battle_frog_faahri
    battleAnimationRiver: fx/river_overlay/battle_frog_river
    battleAnimationWater: units/frog/faahri/battle_frog_swim_faahri
    smallPortrait: units/frog/faahri/portrait_frog_faahri_small.png
    mediumPortrait: units/frog/faahri/portrait_frog_faahri_medium.png
    mapSpeed: 7.0
    grabPos: [14, 75]
    attackTimingsHack: false
    emotes:
      idle: idle
    sounds:
      attackMap: unitAttack
      attack: frogAttack
      death: frogDieYellow
      deathMap: unitDie
      run: frogMapEntryYellow
      runMap: frogMapEntryYellow
      runWater: frogMapWaterEntryYellow
      runMapWater: frogMapWaterEntryYellow
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.5

  - class: frog
    faction: pirates
    name: unit_name_frog_pirates
    mapAnimation: units/frog/pirates/map_frog_pirates
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    mapAnimationWater: units/frog/pirates/map_frog_swim_pirates
    battleAnimation: units/frog/pirates/battle_frog_pirates
    battleAnimationRiver: fx/river_overlay/battle_frog_river
    battleAnimationWater: units/frog/pirates/battle_frog_swim_pirates
    smallPortrait: units/frog/pirates/portrait_frog_pirates_small.png
    mediumPortrait: units/frog/pirates/portrait_frog_pirates_medium.png
    mapSpeed: 7.0
    grabPos: [14, 75]
    attackTimingsHack: false
    emotes:
      idle: idle
    sounds:
      attackMap: unitAttack
      attack: frogAttack
      death: frogDie
      deathMap: unitDie
      run: frogMapEntry
      runMap: frogMapEntry
      runWater: frogMapWaterEntry
      runMapWater: frogMapWaterEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.5
...
