---

weapons:
  - id: giantSlam
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.55
      soldier: 1.35
      villager: 1.35
      spearman: 15
      dog: 1.55
      wagon: 0.8
      knight: 0.9
      trebuchet: 1.1
      ballista: 1.2
      merman: 1.35
      mage: 1.15
      structure: 0.9
      giant: 0.5
      commander: 0.4
      rifleman: 1.45
      thief: 1.35
      
      warship: 0.85
      harpoonship: 1.15
      turtle: 0.95
      travelboat: 1.05
      pirate_ship: 1.15
      flagship: 0.4
      
unitClasses:
  - id: giant
    name: unit_class_name_giant
    cost: 1200
    movement: walking
    moveRange: 5
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: giantSlam
    tags:
      - giant
      - type.ground.heavy
      - tall
    verbs:
      - rescue
      - load
      - pick_up_crown
      - throw_crown
      - healing_potion
    battleUnitCount: 1
    passiveMultiplier: 2
    sightRange: 4
    deathVerbId: death_drop_crown
...
