---

weapons:
  - id: giantSlam
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      buildings: 1

unitClasses:
  - id: giant
    name: unit_class_name_giant
    cost: 1200
    resourceCost: 3
    movement: riding
    moveRange: 5
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: giantSlam
    tags:
      - giant
      - type.ground.heavy
      - tall
    verbs:
      - load
      - rescue
      - attack_AI
      - hire
      - take_crown
    battleUnitCount: 1
    passiveMultiplier: 2.5
    sightRange: 4

units:
  - class: giant
    faction: outlaw
    name: unit_name_giant_outlaw
    mapAnimation: units/giant/outlaw/map_giant_outlaw
    mapLightSource:
      sprite: lights_medium
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_large
      scale: [0.65, 0.35]
      jitter:
        scale: 0.5
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/giant/outlaw/battle_giant_outlaw
    battleAnimationRiver: fx/river_overlay/battle_giant_cherrystone_river
    smallPortrait: units/giant/outlaw/portrait_giant_outlaw_small.png
    mediumPortrait: units/giant/outlaw/portrait_giant_outlaw_medium.png
    mapSpeed: 4.0
    grabPos: [27, 13]
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      preAttack: giantPoseStone
      attack: giantAttack
      attackMap: unitAttack
      death: giantDie
      deathMap: unitDie
      run: giantEntry
      runMap: giantEntry
      hit: hitStone
      hitMap: hitStone
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.75

...