---

weapons:
  - id: giantSlam
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.5
      soldier: 1.3
      villager: 1.8
      spearman: 1
      dog: 1.5
      wagon: 0.75
      knight: 0.9
      trebuchet: 1.05
      ballista: 1.15
      merman: 1.3
      mage: 1.1
      structure: 0.85
      giant: 0.45
      commander: 0.35
      rifleman: 1.4
      thief: 1.3
      
      warship: 0.8
      harpoonship: 1.1
      turtle: 0.9
      travelboat: 1.0
      flagship: 0.25
      
unitClasses:
  - id: giant
    name: unit_class_name_giant
    cost: 1200
    movement: walking
    moveRange: 5
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: giantSlam
    tags:
      - giant
      - type.ground.heavy
      - tall
      - walking
    verbs:
      - rescue
      - load
      - pick_up_crown
      - throw_crown
      - healing_potion
      - wait_ai
      - hire
    battleUnitCount: 1
    passiveMultiplier: 2
    sightRange: 4
    deathVerbId: death

units:
  - class: giant
    faction: outlaw
    name: unit_name_giant_outlaws
    mapAnimation: units/giant/outlaws/map_giant_outlaws
    battleAnimation: units/giant/outlaws/battle_giant_outlaws
    battleAnimationRiver: fx/river_overlay/battle_giant_cherrystone_river
    smallPortrait: units/giant/outlaws/portrait_giant_outlaws_small.png
    mediumPortrait: units/giant/outlaws/portrait_giant_outlaws_medium.png
    mapSpeed: 4.0
    grabPos: [27, 13]
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      preAttack: giantPoseStone
      attack: giantAttack
      attackMap: unitAttack
      death: giantDie
      deathMap: unitDie
      run: giantEntry
      runMap: giantEntry
      hit: hitStone
      hitMap: hitStone
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.75
...
