---
weapons:
  - id: harpoonshipCannon
    rangeMin: 2
    rangeMax: 3
    canMoveAndAttack: true
    baseDamage:
      air: 1
      water: 1
      land: 1
    tagDamage:
      archer: 0.2
      soldier: 0.2
      villager: 0.25
      spearman: 0.15
      dog: 0.2
      wagon: 0.1
      knight: 0.1
      trebuchet: 0.05
      mage: 0.2
      structure: 0.05
      commander: 0.05
      ballista: 0.1
      giant: 0.0001
      rifleman: 0.2
      thief: 0.2
    
      witch: 0.8
      dragon: 0.7
      harpy: 1.3
      balloon: 0.8

      flagship: 0.1
      pirate_ship: 0.2
      warship: 0.15
      harpoonship: 0.3
      turtle: 0.75
      merman: 0.3
      travelboat: 0.45

unitClasses:
  - id: harpoonship
    name: unit_class_name_harpoonship
    cost: 550
    movement: sailing
    moveRange: 6
    damageMultiplier: 1
    uiEffectivenessMultiplier: 2
    aiPriority: 1.0
    weapons:
      - id: harpoonshipCannon
    cargoSpace: 2
    verbs:
      - rescue
      - pick_up_crown
      - throw_crown
      - healing_potion
    tags:
      - harpoonship
      - type.sea
    battleUnitCount: 1
    passiveMultiplier: 1.5
    sightRange: 5

...