---

weapons:
  - id: lance
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1
      soldier: 0.9
      villager: 1.2
      spearman: 0.45
      dog: 1.2
      wagon: 0.55
      knight: 0.55
      trebuchet: 0.9
      ballista: 0.95
      merman: 0.85
      mage: 1.1
      structure: 0.65
      giant: 0.25
      commander: 0.25
      rifleman: 1.0
      thief: 0.9

      warship: 0.2
      harpoonship: 0.3
      turtle: 0.25
      travelboat: 0.25
      pirate_ship: 0.25
      flagship: 0.15
      
unitClasses:
  - id: knight
    name: unit_class_name_knight
    cost: 600
    movement: riding
    moveRange: 6
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: lance
    tags:
      - knight
      - type.ground.heavy
      - riding
    verbs:
      - rescue
      - load
      - pick_up_crown
      - throw_crown
      - healing_potion
      - wait_ai
      - hire
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 3
    deathVerbId: death_drop_crown
    deathVerbId: death
...
