---

weapons:
  - id: lance
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.05
      soldier: 0.95
      villager: 0.95
      spearman: 0.5
      dog: 1.25
      wagon: 0.6
      knight: 0.6
      trebuchet: 0.95
      ballista: 1.0
      merman: 0.9
      mage: 1.15
      structure: 0.7
      giant: 0.3
      commander: 0.3
      rifleman: 1.05
      thief: 0.95

      warship: 0.25
      harpoonship: 0.35
      turtle: 0.3
      travelboat: 0.3
      pirate_ship: 0.3
      flagship: 0.25
      
unitClasses:
  - id: knight
    name: unit_class_name_knight
    cost: 600
    movement: riding
    moveRange: 6
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: lance
    tags:
      - knight
      - type.ground.heavy
    verbs:
      - rescue
      - load
      - pick_up_crown
      - throw_crown
      - healing_potion
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 3
    deathVerbId: death_drop_crown
...
