---

weapons:
  - id: mineWeapon
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: false
    baseDamage:
      water: 1

unitClasses:
  - id: mine
    name: unit_class_name_mine
    movement: sailing
    moveRange: -1
    weapons:
      - id: mineWeapon
    verbs:
      - mine_explode
    tags:
      - mine
      - type.sea
    battleUnitCount: 1
    passiveMultiplier: 1.25
    sightRange: 3
    classIcon: unit_icons_summon
    deathVerbId: mine_death
    ambushedVerbId: mine_trigger
    isUnderwater: true
    canAttack: false
    uiEffectivenessMultiplier: 2


units:
  - class: mine
    faction: cherrystone
    name: unit_class_name_mine
    mapAnimation: units/soldier/cherrystone/map_soldier_cherrystone
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_small
      scale: [1.5, 1.0]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/soldier/cherrystone/battle_soldier_cherrystone_extra
    battleAnimationRiver: fx/river_overlay/battle_soldier_cherrystone_river
    smallPortrait: units/soldier/cherrystone/portrait_soldier_cherrystone_small.png
    mediumPortrait: units/soldier/cherrystone/portrait_soldier_cherrystone_medium.png
    mapSpeed: 4.0
    deathMoveMin: 0
    deathMoveMax: 0
    grabPos: [13, 14]
    stayAfterDeath: true
    sounds:
      death: koji/kojiDroneDie
      run: koji/kojiDroneEntry
      runMap: koji/kojiDroneEntry
      hit: hitMetal
      hitMap: hitMetal
...
