---

weapons:
  - id: bow_hans
    rangeMin: 1
    rangeMax: 3
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
      air: 1
      buildings: 1
    tagDamageOverwrite: archer

unitClasses:
  - id: rival
    name: unit_class_name_minicommander
    cost: 500
    movement: walking
    moveRange: 3
    damageMultiplier: 1
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: bow_hans
    tags:
      - archer
      #- commander
      - type.ground.light
    verbs:
      - load
      - capture
      - capture_AI
      - rescue
      - attack_AI
      - hire
      - take_crown
    battleUnitCount: 1
    passiveMultiplier: 1.5
    sightRange: 4
    canBeRenamed: false
    isCommander: true


units:
  - class: rival
    faction: outlaw
    name: unit_name_rival_outlaws
    mapAnimation: units/archer/cherrystone/map_archer_cherrystone
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/archer/cherrystone/battle_archer_cherrystone
    battleAnimationRiver: fx/river_overlay/battle_archer_river
    smallPortrait: units/archer/cherrystone/portrait_archer_cherrystone_small.png
    mediumPortrait: units/archer/cherrystone/portrait_archer_cherrystone_medium.png
    skinColour: typeII
    mapSpeed: 4.0
    grabPos: [15, 24]
    sounds:
      attackMap: unitAttack
      attack: archerAttack
      attackEffect1: archerAttackEffect1
      attackEffect2: archerAttackEffect2
      attackEffect3: archerAttackEffect3
      attackEffect4: archerAttackEffect4
      captureShout: soldierPreAttackRed
      death: soldierDieRed
      deathMap: unitDie
      run: infantryLightEntry
      runMap: infantryLightMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
      counter: archerCounterAttack
    attacks:
      - id: primary
        attackAnimationSequence: counter
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.8
        attackSound: counter
        samePanel: true
      - id: oneArchers
        hitSpark: fx/bs_stab_attack
        hitDelay: [1.7]
        effect: fx/bs_archer_attack_1
        effectDelay: 1.4
        attackEffectSound: attackEffect1
        numAttackers: 1
        ranged: true
    emotes:
      idle: idle
      dance: emote_dance
      surprise: emote_surprise
    shouts:
      soldier_shout1: soldierShoutRed1
      soldier_shout2: soldierShoutRed2
      soldier_shout3: soldierShoutRed3
      soldier_shout4: soldierShoutRed4
      soldier_shout5: soldierShoutRed5
      soldier_shout6: soldierShoutRed6
      soldier_shout7: soldierShoutRed7
      soldier_shout8: soldierShoutRed8
      soldier_shout9: soldierShoutRed9
      soldier_hit1: soldierHitRed1
      soldier_hit2: soldierHitRed2
      soldier_hit3: soldierHitRed3
      soldier_hit4: soldierHitRed4
      soldier_hit5: soldierHitRed5
    hidden:
      shouts:
        - soldier_shout3
        - soldier_shout5
        - soldier_shout6
        - soldier_shout9

...
