---

weapons:
  - id: pirate_ship_cannon
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 0.9
      soldier: 0.8
      spearman: 0.7
      dog: 0.75
      wagon: 0.6
      knight: 0.2
      trebuchet: 0.75
      ballista: 0.8
      mage: 0.75
      structure: 0.45
      commander: 0.2
      giant: 0.15
      rifleman: 0.95
      thief: 1.05
      
      flagship: 0.35
      pirate_ship: 0.6
      warship: 0.5
      harpoonship: 0.75
      turtle: 0.15
      travelboat: 0.7
      merman: 0.25
unitClasses:
  - id: pirate_ship
    name: unit_class_name_pirate_ship
    cost: 600
    classIconSpritesheet: ui_RagnarokMod
    movement: sailing
    moveRange: 7
    damageMultiplier: 1
    aiPriority: 3
    weapons:
      - id: pirate_ship_cannon
    cargoSpace: 2
    tags:
      - pirate_ship
      - type.sea
    startingStates:
      - id: gold
        value: 0

    verbs:
      - rescue
      - pick_up_crown
      - throw_crown
      - pirate_steal
      - healing_potion
#      - betterMerge
    battleUnitCount: 1
    passiveMultiplier: 1.5
    sightRange: 5
    isHiddenInCutsceneEditor: true

units:
  - class: pirate_ship
    faction: outlaw
    name: unit_name_pirate_ship_outlaws
    mapAnimation: units/raider/cherrystone/map_raider_cherrystone
    battleAnimation: units/warship/cherrystone/battle_warship_cherrystone
    smallPortrait: units/raider/cherrystone/portrait_raider_cherrystone_small.png
    mediumPortrait: units/raider/cherrystone/portrait_raider_cherrystone_medium.png
    mapSpeed: 6.0
    grabPos: [10, 9]
    deathMoveMin: 80
    deathMoveMax: 80
    sounds:
      attackMap: unitAttack
      attack: warshipAttack
      attackEffect: warshipAttackEffect
      death: shipDie
      deathMap: unitDie
      run: waterBoatEntry
      runMap: waterBoatEntry
      hit: hitWood
      hitMap: hitWood
    attacks:
      - id: primary
        hitDelay: 2.0
        hitSpark: fx/bs_stab_attack
        ranged: true
        effect: fx/bs_warship_attack
        effectDelay: 1.8
        hitDelay: [2.0, 2.3, 2.6]
