---

weapons:
  - id: sword
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      buildings: 1
    tagDamageOverwrite: soldier

unitClasses:
  - id: soldier
    name: unit_class_name_soldier
    cost: 100
    movement: walking
    moveRange: 4
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: sword
    verbs:
      - capture
      - load
      - pick_up_crown
      - hand_over_crown
      - throw_crown
      - rescue
      - hire
    tags:
      - soldier
      - type.ground.light
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 4
...
