---

units:
  - class: spearman
    faction: outlaw
    name: unit_name_spearman_outlaw
    mapAnimation: units/spearman/outlaw/map_spearman_outlaw
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/spearman/outlaw/battle_spearman_outlaw
    battleAnimationRiver: fx/river_overlay/battle_spearman_cherrystone_river
    smallPortrait: units/spearman/outlaw/portrait_spearman_outlaw_small.png
    mediumPortrait: units/spearman/outlaw/portrait_spearman_outlaw_medium.png
    mapSpeed: 4.0
    grabPos: [18, 12]
    emotes:
      idle: idle
    sounds:
      attackMap: unitAttack
      attack: soldierAttackRed
      attackShout: soldierPreAttackRed
      captureShout: soldierPreAttackRed
      death: soldierDieRed
      deathMap: unitDie
      run: infantryHeavyEntry
      runMap: infantryHeavyMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.4
    shouts:
      soldier_shout1: soldierShoutRed1
      soldier_shout2: soldierShoutRed2
      soldier_shout3: soldierShoutRed3
      soldier_shout4: soldierShoutRed4
      soldier_shout5: soldierShoutRed5
      soldier_shout6: soldierShoutRed6
      soldier_shout7: soldierShoutRed7
      soldier_shout8: soldierShoutRed8
      soldier_shout9: soldierShoutRed9
      soldier_hit1: soldierHitRed1
      soldier_hit2: soldierHitRed2
      soldier_hit3: soldierHitRed3
      soldier_hit4: soldierHitRed4
      soldier_hit5: soldierHitRed5

...