---

unitClasses:
  - id: thief_with_gold
    name: unit_class_name_thief_with_gold
    cost: 400
    movement: walking
    moveRange: 3
    damageMultiplier: 1
    aiPriority: 2.5
    weapons: []
    verbs:
      - load
      - deposit
      - bypass_gate
      - drop
      - rescue
      - attack_AI
      - hire
      - take_crown
    tags:
      - thief
      - type.ground.hideout
    battleUnitCount: 1
    isRecruitable: false
    appearsInLists: false
    inPalette: false
    sightRange: 4
    deathVerbId: death_give_gold
    codexClass: thief


units:
  - class: thief_with_gold
    faction: cherrystone
    name: unit_name_thief_with_gold_cherrystone
    mapAnimation: units/thief/cherrystone/map_thief_gold_cherrystone2
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/thief/cherrystone/battle_thief_gold_cherrystone2
    battleAnimationRiver: fx/river_overlay/battle_thief_river
    smallPortrait: units/thief/cherrystone/portrait_thief_cherrystone_small2.png
    mediumPortrait: units/thief/cherrystone/portrait_thief_cherrystone_medium2.png
    mapSpeed: 4.0
    grabPos: [13, 14]
    deathMoveMin: 0
    deathMoveMax: 0
    stayAfterDeath: true
    sounds:
      death: thiefLoadedDieRed
      deathMap: unitDie
      run: thiefLoadedMapEntry
      runMap: thiefLoadedMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    shouts:
      soldier_shout1: soldierShoutRed1
      soldier_shout2: soldierShoutRed2
      soldier_shout3: soldierShoutRed3
      soldier_shout4: soldierShoutRed4
      soldier_shout5: soldierShoutRed5
      soldier_shout6: soldierShoutRed6
      soldier_shout7: soldierShoutRed7
      soldier_shout8: soldierShoutRed8
      soldier_shout9: soldierShoutRed9
      soldier_hit1: soldierHitRed1
      soldier_hit2: soldierHitRed2
      soldier_hit3: soldierHitRed3
      soldier_hit4: soldierHitRed4
      soldier_hit5: soldierHitRed5
    hidden:
      shouts:
        - soldier_shout3
        - soldier_shout5
        - soldier_shout6
        - soldier_shout9
    emotes:
      idle: idle

  - class: thief_with_gold
    faction: outlaw
    name: unit_name_thief_with_gold_outlaw
    mapAnimation: units/thief/cherrystone/map_thief_gold_cherrystone
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/thief/cherrystone/battle_thief_gold_cherrystone
    battleAnimationRiver: fx/river_overlay/battle_thief_river
    smallPortrait: units/thief/cherrystone/portrait_thief_cherrystone_small.png
    mediumPortrait: units/thief/cherrystone/portrait_thief_cherrystone_medium.png
    mapSpeed: 4.0
    grabPos: [13, 14]
    deathMoveMin: 0
    deathMoveMax: 0
    stayAfterDeath: true
    sounds:
      death: thiefLoadedDieRed
      deathMap: unitDie
      run: thiefLoadedMapEntry
      runMap: thiefLoadedMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    shouts:
      soldier_shout1: soldierShoutRed1
      soldier_shout2: soldierShoutRed2
      soldier_shout3: soldierShoutRed3
      soldier_shout4: soldierShoutRed4
      soldier_shout5: soldierShoutRed5
      soldier_shout6: soldierShoutRed6
      soldier_shout7: soldierShoutRed7
      soldier_shout8: soldierShoutRed8
      soldier_shout9: soldierShoutRed9
      soldier_hit1: soldierHitRed1
      soldier_hit2: soldierHitRed2
      soldier_hit3: soldierHitRed3
      soldier_hit4: soldierHitRed4
      soldier_hit5: soldierHitRed5
    hidden:
      shouts:
        - soldier_shout3
        - soldier_shout5
        - soldier_shout6
        - soldier_shout9
    emotes:
      idle: idle

...