---
unitClasses:
  - id: travelboat
    name: unit_class_name_travelboat
    cost: 200
    movement: sailing
    moveRange: 8
    damageMultiplier: 1
    aiPriority: 1.5
    weapons: []
    tags:
      - travelboat
      - transport
      - type.sea
      - sailing
    verbs:
      - rescue
      - unload
      - pick_up_crown
      - throw_crown
      - healing_potion
      - wait_ai
    battleUnitCount: 1
    loadCapacity: 2
    sightRange: 3
    transportTags: [ type.ground.light, type.ground.heavy, type.amphibious, type.ground.hideout ]
    isHiddenInCutsceneEditor: true
    deathVerbId: death
...