---

weapons:
  - id: turtleBite
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    terrainExclusion:
      - plains
      - plains_alt
      - bridge
      - carpet
      - city
      - cobblestone
      - forest
      - forest_alt
      - mountain
      - road
      - rough
      - cave_bridge
    baseDamage:
      water: 1
      land: 1
    tagDamage:
    
      archer: 0.5
      soldier: 0.45
      villager: 0.5
      spearman: 0.4
      dog: 0.5
      wagon: 0
      knight: 0.2
      trebuchet: 0
      ballista: 0
      mage: 0.4
      structure: 0.1
      giant: 0.1
      commander: 0.2
      rifleman: 0.4
      thief: 0.5

      warship: 0.8
      harpoonship: 0.35
      turtle: 0.50
      travelboat: 0.55
      merman: 1.1
      flagship: 0.35
      pirate_ship: 0.75

unitClasses:
  - id: turtle
    name: unit_class_name_turtle
    cost: 400
    movement: sailing
    moveRange: 8
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: turtleBite
    tags:
      - turtle
      - type.sea
    verbs:
      - pick_up_crown
      - throw_crown
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 4
    scout: true
...