---

weapons:
  - id: turtleBite
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      water: 1
      land: 1
    tagDamage:
    
      archer: 0.3
      soldier: 0.25
      villager: 0.4
      spearman: 0.2
      dog: 0.3
      wagon: 0
      knight: 0.15
      trebuchet: 0
      ballista: 0
      mage: 0.25
      structure: 0.1
      giant: 0.05
      commander: 0.15
      rifleman: 0.25
      thief: 0.3

      warship: 0.8
      harpoonship: 0.35
      turtle: 0.5
      travelboat: 0.55
      merman: 1.1
      flagship: 0.25

unitClasses:
  - id: turtle
    name: unit_class_name_turtle
    cost: 400
    movement: sailing
    moveRange: 8
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: turtleBite
    tags:
      - turtle
      - type.sea
      - type.scout
      - sailing
    verbs:
      - rescue
      - pick_up_crown
      - throw_crown
      - healing_potion
      - wait_ai
      - hire
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 4
    scout: true
    deathVerbId: death

units:
  - class: turtle
    enabled: true
    faction: cherrystone
    name: unit_name_turtle_cherrystone
    mapAnimation: units/turtle/cherrystone/map_turtle_cherrystone
    battleAnimation: units/turtle/cherrystone/battle_turtle_cherrystone
    smallPortrait: units/turtle/cherrystone/portrait_turtle_cherrystone_small.png
    mediumPortrait: units/turtle/cherrystone/portrait_turtle_cherrystone.png
    mapSpeed: 4.0
    grabPos: [13, 19]
    sounds:
      attackMap: unitAttack
      attack: turtleAttack
      attackEffect: waveCrash
      attackShout: soldierPreAttackRed
      death: merfolkDie
      deathMap: unitDie
      run: waterEntry
      runMap: waterMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        effectDelay: 2
        hitDelay: 2.2
        effect: fx/bs_turtle_attack
        ranged: true

  - class: turtle
    enabled: true
    faction: felheim
    name: unit_name_turtle_felheim
    mapAnimation: units/turtle/felheim/map_turtle_felheim
    battleAnimation: units/turtle/felheim/battle_turtle_felheim
    smallPortrait: units/turtle/felheim/portrait_turtle_felheim_small.png
    mediumPortrait: units/turtle/felheim/portrait_turtle_felheim.png
    mapSpeed: 4.0
    grabPos: [13, 19]
    sounds:
      attackMap: unitAttack
      attack: turtleAttack
      attackEffect: waveCrash
      attackShout: soldierPreAttackRed
      death: merfolkDie
      deathMap: unitDie
      run: waterEntry
      runMap: waterMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        effectDelay: 2
        hitDelay: 2.2
        effect: fx/bs_turtle_attack
        ranged: true


  - class: turtle
    enabled: true
    faction: heavensong
    name: unit_name_turtle_heavensong
    mapAnimation: units/turtle/heavensong/map_turtle_heavensong
    battleAnimation: units/turtle/heavensong/battle_turtle_heavensong
    smallPortrait: units/turtle/heavensong/portrait_turtle_heavensong_small.png
    mediumPortrait: units/turtle/heavensong/portrait_turtle_heavensong.png
    mapSpeed: 4.0
    grabPos: [13, 19]
    sounds:
      attackMap: unitAttack
      attack: turtleAttackYellow
      attackEffect: waveCrash
      attackShout: soldierPreAttackRed
      death: soldierDieYellow
      deathMap: unitDie
      run: waterEntry
      runMap: waterMapEntry
      hit: hitOrganic
      hitMap: hitWood
    attacks:
      - id: primary
        effectDelay: 2
        hitDelay: 2.2
        effect: fx/bs_turtle_attack
        ranged: true



  - class: turtle
    enabled: true
    faction: floran
    name: unit_name_turtle_floran
    mapAnimation: units/turtle/floran/map_turtle_floran
    battleAnimation: units/turtle/floran/battle_turtle_floran
    smallPortrait: units/turtle/floran/portrait_turtle_floran_small.png
    mediumPortrait: units/turtle/floran/portrait_turtle_floran.png
    mapSpeed: 4.0
    grabPos: [13, 19]
    sounds:
      attackMap: unitAttack
      attack: turtleAttackGreen
      attackEffect: waveCrash
      attackShout: soldierPreAttackRed
      death: soldierDieGreen
      deathMap: unitDie
      run: waterEntry
      runMap: waterMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        effectDelay: 2
        hitDelay: 2.2
        effect: fx/bs_turtle_attack
        ranged: true


  - class: turtle
    enabled: true
    faction: outlaw
    name: unit_name_turtle_outlaws
    mapAnimation: units/turtle/outlaws/map_turtle_outlaws
    battleAnimation: units/turtle/outlaws/battle_turtle_outlaws
    smallPortrait: units/turtle/outlaws/portrait_turtle_outlaws_small.png
    mediumPortrait: units/turtle/outlaws/portrait_turtle_outlaws.png
    mapSpeed: 4.0
    grabPos: [13, 19]
    sounds:
      attackMap: unitAttack
      attack: turtleAttack
      attackEffect: waveCrash
      attackShout: soldierPreAttackRed
      death: merfolkDie
      deathMap: unitDie
      run: waterEntry
      runMap: waterMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    attacks:
      - id: primary
        effectDelay: 2
        hitDelay: 2.2
        effect: fx/bs_turtle_attack
        ranged: true

...