---

weapons:
  - id: turtleBite
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      water: 1
      land: 1
    tagDamage:
    
      archer: 0.3
      soldier: 0.25
      villager: 0.3
      spearman: 0.2
      dog: 0.3
      wagon: 0
      knight: 0.15
      trebuchet: 0
      ballista: 0
      mage: 0.25
      structure: 0.1
      giant: 0.05
      commander: 0.15
      rifleman: 0.25
      thief: 0.3

      warship: 0.8
      harpoonship: 0.35
      turtle: 0.5
      travelboat: 0.55
      merman: 1.1
      flagship: 0.25
      pirate_ship: 0.75

unitClasses:
  - id: turtle
    name: unit_class_name_turtle
    cost: 400
    movement: sailing
    moveRange: 8
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: turtleBite
    tags:
      - turtle
      - type.sea
      - type.scout
      - sailing
    verbs:
      - rescue
      - pick_up_crown
      - throw_crown
      - healing_potion
      - wait_ai
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 5
    scout: true
    deathVerbId: death
...