---

weapons:
  - id: turtleBite
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      water: 1
      land: 1
    tagDamage:
    
      archer: 0.35
      soldier: 0.3
      villager: 0.35
      spearman: 0.25
      dog: 0.35
      wagon: 0
      knight: 0.2
      trebuchet: 0
      ballista: 0
      mage: 0.3
      structure: 0.15
      giant: 0.1
      commander: 0.2
      rifleman: 0.3
      thief: 0.35

      warship: 0.85
      harpoonship: 0.4
      turtle: 0.55
      travelboat: 0.6
      merman: 1.15
      flagship: 0.4
      pirate_ship: 0.8

unitClasses:
  - id: turtle
    name: unit_class_name_turtle
    cost: 400
    movement: sailing
    moveRange: 8
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: turtleBite
    tags:
      - turtle
      - type.sea
      - type.scout
    verbs:
      - rescue
      - pick_up_crown
      - throw_crown
      - healing_potion
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 5
    scout: true
...