---

unitClasses:
  - id: villager
    name: unit_class_name_villager
    cost: 50
    movement: walking
    moveRange: 3
    damageMultiplier: 1
    canBeReinforced: false
    aiPriority: 0.5
    weapons: []
    verbs:
      - load
      - rescue
      - attack_AI
      - hire
      - take_crown
    tags:
      - villager
      - type.ground.light
    battleUnitCount: 4
    sightRange: 4
    isRecruitable: false
    palettePriority: 1

units:
  - class: villager
    faction: cherrystone
    name: unit_name_villager_cherrystone
    mapAnimation: units/villager/cherrystone/map_villager_cherrystone
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/villager/cherrystone/battle_villager_cherrystone
    battleAnimationRiver: fx/river_overlay/battle_villager_river
    smallPortrait: units/villager/cherrystone/portrait_villager_cherrystone_small.png
    mediumPortrait: units/villager/cherrystone/portrait_villager_cherrystone_medium.png
    mapSpeed: 4.0
    grabPos: [13, 14]
    sounds:
      death: soldierDieRed
      deathMap: unitDie
      run: infantryLightEntry
      runMap: infantryLightMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    shouts:
      soldier_shout1: soldierShoutRed1
      soldier_shout2: soldierShoutRed2
      soldier_shout3: soldierShoutRed3
      soldier_shout4: soldierShoutRed4
      soldier_shout5: soldierShoutRed5
      soldier_shout6: soldierShoutRed6
      soldier_shout7: soldierShoutRed7
      soldier_shout8: soldierShoutRed8
      soldier_shout9: soldierShoutRed9
      soldier_hit1: soldierHitRed1
      soldier_hit2: soldierHitRed2
      soldier_hit3: soldierHitRed3
      soldier_hit4: soldierHitRed4
      soldier_hit5: soldierHitRed5
      crownbearer_panting: cutscene/crownbearerPanting
      crownbearer_yell: cutscene/crownbearerYell
      villager_male_shout1: cutscene/villagerScreamMale1
      villager_male_shout2: cutscene/villagerScreamMale2
      villager_female_shout1: cutscene/villagerScreamFemale1
      villager_female_shout2: cutscene/villagerScreamFemale2
    emotes:
      idle: idle
      idle_old: emote_old_idle
      cower: emote_cower
      idle_gold: emote_idle_gold
      throw_gold: emote_throw_gold
      old_pushed: emote_old_pushed
    alternativeRuns:
      - id: run_gold
      - id: run_old

  - class: villager
    faction: outlaw
    name: unit_name_villager_outlaw
    mapAnimation: units/villager/outlaw/map_villager_outlaw
    mapLightSource:
      sprite: lights_small
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.75
        frequency: 0.3
        frequencyVariance: 0.15
    battleAnimation: units/villager/outlaw/battle_villager_outlaw
    battleAnimationRiver: fx/river_overlay/battle_villager_river
    smallPortrait: units/villager/outlaw/portrait_villager_outlaw_small.png
    mediumPortrait: units/villager/outlaw/portrait_villager_outlaw_medium.png
    mapSpeed: 4.0
    grabPos: [13, 14]
    sounds:
      death: soldierDieRed
      deathMap: unitDie
      run: infantryLightEntry
      runMap: infantryLightMapEntry
      hit: hitOrganic
      hitMap: hitOrganic
    shouts:
      soldier_shout1: soldierShoutRed1
      soldier_shout2: soldierShoutRed2
      soldier_shout3: soldierShoutRed3
      soldier_shout4: soldierShoutRed4
      soldier_shout5: soldierShoutRed5
      soldier_shout6: soldierShoutRed6
      soldier_shout7: soldierShoutRed7
      soldier_shout8: soldierShoutRed8
      soldier_shout9: soldierShoutRed9
      soldier_hit1: soldierHitRed1
      soldier_hit2: soldierHitRed2
      soldier_hit3: soldierHitRed3
      soldier_hit4: soldierHitRed4
      soldier_hit5: soldierHitRed5
      crownbearer_panting: cutscene/crownbearerPanting
      crownbearer_yell: cutscene/crownbearerYell
      villager_male_shout1: cutscene/villagerScreamMale1
      villager_male_shout2: cutscene/villagerScreamMale2
      villager_female_shout1: cutscene/villagerScreamFemale1
      villager_female_shout2: cutscene/villagerScreamFemale2
    emotes:
      idle: idle
      idle_old: emote_old_idle
      cower: emote_cower
      idle_gold: emote_idle_gold
      throw_gold: emote_throw_gold
      old_pushed: emote_old_pushed
    alternativeRuns:
      - id: run_gold
      - id: run_old

...