---
weapons:
  - id: warshipCannon
    rangeMin: 2
    rangeMax: 4
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.05
      soldier: 0.95
      villager: 1.05
      spearman: 0.75
      dog: 1.05
      wagon: 0.65
      knight: 0.75
      trebuchet: 0.85
      ballista: 0.9
      mage: 0.85
      structure: 0.8
      giant: 0.6
      commander: 0.3
      rifleman: 1.15
      thief: 1.05

      warship: 0.6
      turtle: 0.35
      harpoonship: 0.85
      merman: 0.8
      travelboat: 0.7
      flagship: 0.3
      pirate_ship: 0.75
      
unitClasses:
  - id: warship
    name: unit_class_name_warship
    cost: 1000
    movement: sailing
    moveRange: 5
    damageMultiplier: 1
    aiPriority: 1.0
    weapons:
      - id: warshipCannon
    cargoSpace: 2
    tags:
      - warship
      - type.sea
    verbs:
      - rescue
      - pirate_claim
      - pick_up_crown
      - throw_crown
      - healing_potion
    battleUnitCount: 1
    passiveMultiplier: 1.5
    sightRange: 5
    isHiddenInCutsceneEditor: true
...