---
 
weapons:
  - id: witchSpell
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      air: 1
    tagDamage:
      witch: 0.4
      dragon: 0.4
      harpy: 0.65
      balloon: 0.55


unitClasses:
  - id: witch
    name: unit_class_name_witch
    cost: 800
    movement: flying
    moveRange: 7
    damageMultiplier: 1.0
    aiPriority: 1.0
    weapons:
      - id: witchSpell
    tags:
      - witch
      - type.air
      - spellcaster
    verbs:
      - rescue
      - spell_hex
      - pick_up_crown
      - throw_crown
      - healing_potion
    battleUnitCount: 4
    passiveMultiplier: 2.0
    sightRange: 6
    canSeeOverTerrain: true

...
