---

triggerActions:
  - id: ai_set_no_building_attacking
    parameters:
      - type: player

  - id: ai_set_priority_target
    parameters:
      - type: player
      - type: location
      - type: integer

  - id: enable_hiring
    parameters:
      - type: player
      
  - id: allow_pirate_ships
    parameters:
      - type: player
      
  - id: set_match_seed
    parameters:
      - type: integer
      
  - id: reveal_all
    parameters:
      - type: player
      - type: location

  - id: reveal_all_but_hidden
    parameters:
      - type: player
      - type: location
      
  - id: reveal_all_but_over
    parameters:
      - type: player
      - type: location
      
  - id: enable_AI_fog_limitations

  - id: set_state
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: string
      - type: string

  - id: spawn_unit_in_transport
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: unit_class
      - type: player_neutral_star
      - type: integer

  - id: spawn_unit_close
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: boolean

  - id: split_into
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: unit_class_star

  - id: give_bounty
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star

  - id: give_bounty_based_on_value
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: player_neutral_star
      - type: integer


  - id: link_gizmo_state_with_activators
    parameters:
      - type: location_star
      - type: boolean

  - id: gizmo_active_when_stood_on
    parameters:
      - type: location_star
      - type: boolean

  - id: gizmo_toggle_when_stood_on
    parameters:
      - type: location_star

  - id: invert_gizmo
    parameters:
      - type: location_star
      - type: boolean

  - id: set_threat_at_location
    parameters:
      - type: location_star
      - type: integer
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star

  - id: give_crown
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      
  - id: place_crown
    parameters:
      - type: location_star
      
  - id: set_location_to_vision
    parameters:
      - type: location
      - type: player_neutral_star
      
  - id: set_location_to_spawned
    parameters:
      - type: location
      
  - id: set_location_to_units
    parameters:
      - type: location
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star

  - id: set_location_to_units_with_state
    parameters:
      - type: location
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: string
      - type: string

  - id: transfer_gold_robbed
    parameters:
      - type: player
      - type: transfer_type
      - type: counter
      
  - id: log_message
    parameters:
      - type: string
      
  - id: log_unit
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star

  - id: message
    parameters:
      - type: string
      
  - id: message_counter
    parameters:
      - type: string
      - type: counter

  - id: dialogue_box_with_counter
    parameters:
      - type: character_expression
      - type: character_non_playable
      - type: string
      - type: string
      - type: counter

  - id: dialogue_box
    parameters:
      - type: character_expression
      - type: character_non_playable
      - type: string
      - type: string
  - id: dialogue_box_unit
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: character_expression
      - type: string
      - type: string
  - id: change_objective_with_3_counters
    parameters:
      - type: counter
      - type: counter
      - type: counter
      - type: counter
      - type: counter
      
  - id: modify_healing_potion_count
    parameters:
      - type: player_neutral_star
      - type: operation
      - type: integer
      
  - id: set_priority_target
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: location
      - type: string

  - id: set_facing
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: boolean

  - id: display_path
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star

  - id: let_neutral_units_move

  - id: set_current_position_as_goal
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star

  - id: set_position_as_goal
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: location_star
      - type: integer
      - type: string

  - id: set_awareness
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: string
      - type: boolean
      - type: location_star
      
  - id: update_awareness
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star

  - id: play_animation
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: string
      - type: string

  - id: play_emote
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: string
      - type: string

  - id: force_move
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: location_star

  - id: force_attack
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      
  - id: force_smoke
    parameters:
      - type: location
      - type: player_neutral
      - type: location
      
  - id: force_golf
    parameters:
      - type: location
      - type: player_neutral
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: location

  - id: run_group_sequentially
  - id: run_group_concurrently
  - id: end_group
  - id: set_hide_and_seek
    parameters:
      - type: boolean
      - type: player
  - id: set_hide_and_seek_bravery
    parameters:
      - type: integer
      - type: player
  - id: limit_bounds
    parameters:
      - type: location
      - type: player

#Normally hidden triggers
  - id: set_conditional_location_highlight
    parameters:
      - type: location_real
      - type: location_highlight
      - type: player_colour_star
      - type: boolean
      - type: highlight_condition
      
  - id: force_action
    parameters:
      - type: location_star
      - type: string
      - type: location_star
      - type: location_star      
      - type: boolean
      - type: character_expression
      - type: character
      - type: string

  - id: force_open_ui_tutorial
    parameters:
      - type: tutorial_ui_script
      - type: location_star
      - type: character_expression
      - type: character
      - type: string
      - type: map_flag_star
      - type: boolean

  - id: add_ui_tutorial
    parameters:
      - type: tutorial_ui_script
      - type: location_star
      - type: map_flag_star
      - type: boolean

  - id: queue_force_action
    parameters:
      - type: location_star
      - type: string
      - type: location_star
      - type: location_star      
      - type: boolean
      - type: character_expression
      - type: character
      - type: string

  - id: queue_force_open_ui_tutorial
    parameters:
      - type: tutorial_ui_script
      - type: location_star
      - type: character_expression
      - type: character
      - type: string
      - type: map_flag_star
      - type: boolean
...
