---

triggerConditions:
  - id: state
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: string
      - type: string

  - id: crown_present
    parameters:
      - type: location_star
      
  - id: did_it_occur
    parameters:
      - type: string
      
  - id: is_rescued
    parameters:
      - type: location_star
      - type: player_neutral_star
  - id: or_group
  - id: end_group
...