---

cutscene_props:
  - id: "rays"
    path: "props/rays"
  - id: "outlawHQ_intro_groundlight"
    path: "props/groundlight"
  - id: "outlawHQ_intro_windowlight"
    path: "props/windowlight"
  - id: outlaw_HQ_banner
    path: props/outlaw_HQ_banner
  - id: sleeping_dog_prop
    path: props/sleeping_dog
  - id: crown
    path: props/crown
  - id: one_sec_fade_in
    path: props/one_sec_fade_in
    
  - id: cherrystone_building_background
    path: props/cherrystone_building_background
  - id: cherrystone_building_foreground
    path: props/cherrystone_building_foreground
  - id: telescope
    path: props/telescope
  - id: bush2
    path: props/bush2
  - id: telescope_with_building
    path: props/telescope_with_building
  - id: forge_flame
    path: props/forge_flames
  - id: large_table
    path: props/large_table
  - id: large_table_servings
    path: props/large_table_servings

  - id: outlawship_sail
    path: props/outlawship_sail_2
  - id: cherryship_sail
    path: props/cherryship_sail_2
    
...