---
# default height: 34
cutscene_backgrounds:
  - id: deck
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    background: deck_background
  - id: vesper_ship
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: outlaw_ship_foreground
    background: outlaw_ship_background
  - id: vesper_ship_right
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: outlaw_ship_right_foreground
    background: outlaw_ship_right_background
  - id: vesper_cherry_ship
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: outlaw_and_cherrystone_ship_foreground
    background: outlaw_and_cherrystone_ship_background
  - id: outlaw_ship
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: outlaw_ship_black_foreground
    background: outlaw_ship_black_background
  - id: outlaw_HQ
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: outlawHQ_foreground
    background: outlawHQ_background
  - id: outlaw_HQ_intro
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    background: outlawHQ_intro_background
  - id: sand_cave
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: cave_battlescreen_sand_foreground
    background: cave_battlescreen_sand_background
  - id: tropical_beach
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: tropical_beach_foreground
    background: tropical_beach_background
  - id: tropical_beach_telescope
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    background: tropical_fake_sand_background
  - id: sand_forest_edited
    hidden: true
    spritesheet: backgrounds/sand_battlescreen_extendedbackgrounds
    foreground: sand_battlescreen_extendedbackgrounds_forest_foreground
    background: sand_battlescreen_extendedbackgrounds_forest_edited
  - id: forge
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: heaven_song_smith_foreground
    background: heaven_song_smith_background
  - id: quay
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    background: cutscene_quay_background
    tileHeight: 44

  - id: grass_forest_scene
    spritesheet: backgrounds/map_backgrounds_RagnarokMod
    foreground: grass_forest_scene_foreground
    background: grass_forest_scene_background
    tileHeight: 22