---

commanders:
  - id: duchess
    name: character_duchess_name
    title: character_duchess_title
    playable: true
    faction: cherrystone
    factionIndex: 3
    portrait:
      neutral: portraits/commanders/small/duchess_portrait_small.png
      happy: portraits/commanders/small/duchess_portrait_happy.png
      sad: portraits/commanders/small/duchess_portrait_sad.png
    cutscenePortrait: portraits/commanders/big/duchess_portrait
    portraitOffset: [0, -15]
    namePlate: ui/character_select/charlabel/charlabel_cherrystone.png
    themeSong: music/hostile
    skinColour: typeVI
    unitClassId: commander_duchess
    selectionSound: duchess/duchessShoutIllMakeThisQuick
    dialogueBoxVoice: ui/dialogue/textScrollTenri

  - id: rival
    name: character_rival_name
    title: character_rival_title
    faction: outlaw_rival
    portrait:
      neutral: portraits/commanders/small/rival_portrait_small.png
      happy: portraits/commanders/small/rival_portrait_small.png
      sad: portraits/commanders/small/rival_portrait_small.png
    cutscenePortrait: portraits/commanders/big/rival_portrait
    portraitOffset: [0, 20]
    themeSong: music/hostile
    skinColour: typeII
    unitClassId: rival
    dialogueBoxVoice: ui/dialogue/textScroll
    
  - id: flagship_rival
    name: character_rival_name
    playable: false
    hidden: true
    title: character_rival_title
    faction: outlaw_rival
    portrait:
      neutral: portraits/commanders/small/rival_portrait_small.png
      happy: portraits/commanders/small/rival_portrait_small.png
      sad: portraits/commanders/small/rival_portrait_small.png
    cutscenePortrait: portraits/commanders/big/rival_portrait
    portraitOffset: [0, 20]
    themeSong: music/hostile
    skinColour: typeII
    unitClassId: commander_flagship_rival
    dialogueBoxVoice: ui/dialogue/textScroll

  - id: generic_soldier
    name: character_generic_soldier_name
    faction: cherrystone
    playable: false
    portrait:
        extra: portraits/commanders/small/soldier_portrait_extra.png
        happy: portraits/commanders/small/soldier_portrait_happy.png
        neutral: portraits/commanders/small/soldier_portrait_small.png
        sad: portraits/commanders/small/soldier_portrait_sad.png
    cutscenePortrait: portraits/commanders/big/cherrystone_portrait
    portraitOffset: [0, 20]
    themeSong: music/hostile
    skinColour: typeVI
    unitClassId: soldier
    dialogueBoxVoice: ui/dialogue/textScroll

  - id: generic_soldier2
    name: character_generic_soldier2_name
    faction: heavensong
    playable: false
    portrait:
        extra: portraits/commanders/small/floran_soldier_portrait.png
        happy: portraits/commanders/small/soldier2_portrait_happy.png
        neutral: portraits/commanders/small/soldier2_portrait_small.png
        sad: portraits/commanders/small/felheim_soldier_portrait.png
    cutscenePortrait: portraits/commanders/big/cherrystone_portrait
    portraitOffset: [0, 20]
    themeSong: music/hostile
    skinColour: typeII
    unitClassId: soldier
    dialogueBoxVoice: ui/dialogue/textScroll

  - id: generic_soldier3
    name: character_generic_soldier3_name
    faction: cherrystone
    playable: false
    portrait:
        happy: portraits/commanders/small/merfolk_portrait.png
        neutral: portraits/commanders/small/mage_portrait.png
        sad: portraits/commanders/small/thief_portrait.png
    cutscenePortrait: portraits/commanders/big/cherrystone_portrait
    portraitOffset: [0, 20]
    themeSong: music/hostile
    skinColour: typeII
    unitClassId: soldier
    dialogueBoxVoice: ui/dialogue/textScroll

  - id: generic_villager
    name: unit_class_name_villager
    faction: cherrystone
    playable: false
    portrait:
        extra: portraits/commanders/small/villager_felheim_portrait.png
        happy: portraits/commanders/small/villager_portrait_happy.png
        neutral: portraits/commanders/small/villager_portrait_small.png
        sad: portraits/commanders/small/villager_portrait_sad.png
    cutscenePortrait: portraits/commanders/big/cherrystone_portrait
    portraitOffset: [0, 20]
    themeSong: music/hostile
    skinColour: typeII
    unitClassId: soldier
    dialogueBoxVoice: ui/dialogue/textScroll

  - id: generic_villager_neutral
    name: character_villager_neutral_name
    faction: cherrystone
    playable: false
    portrait:
      neutral: portraits/commanders/small/villager_neutral_portrait_small.png
      happy: portraits/commanders/small/villager_neutral_portrait_happy.png
      sad: portraits/commanders/small/villager_neutral_portrait_sad.png
      extra: portraits/commanders/small/villager_felheim_portrait.png
    cutscenePortrait: portraits/commanders/big/cherrystone_portrait
    themeSong: music/hostile
    skinColour: typeII
    unitClassId: knight
    dialogueBoxVoice: ui/dialogue/textScroll

  - id: empty
    name: unit_class_name_rival
    faction: outlaw
    playable: false
    portrait:
      neutral: portraits/commanders/small/rival_portrait_small.png
      happy: portraits/commanders/small/rival_portrait_small.png
      sad: portraits/commanders/small/rival_portrait_small.png
    cutscenePortrait: portraits/commanders/big/empty
    portraitOffset: [0, 0]
    themeSong: music/hostile
    skinColour: typeVI
    unitClassId: soldier
    dialogueBoxVoice: ui/dialogue/textScroll

  - id: wulfar_offset
    name: character_wulfar_name
    title: character_wulfar_title
    playable: false
    faction: outlaw
    factionIndex: 0
    portrait:
      neutral: portraits/commanders/small/wulfar_portrait_small.png
      happy: portraits/commanders/small/wulfar_portrait_happy.png
      sad: portraits/commanders/small/wulfar_portrait_sad.png
    cutscenePortrait: portraits/commanders/big/wulfar_portrait
    portraitOffset: [50, -45]
    namePlate: ui/character_select/charlabel/charlabel_outlaw.png
    themeSong: music/wulfar
    skinColour: typeII
    unitClassId: commander_wulfar
    selectionSound: wulfar/wulfarShoutUpForTheTask
    dialogueBoxVoice: ui/dialogue/textScrollWulfar

  - id: flagship_wulfar
    name: character_wulfar_name
    title: character_wulfar_title
    playable: false
    hidden: true
    faction: outlaw
    factionIndex: 0
    portrait:
      neutral: portraits/commanders/small/wulfar_portrait_small.png
      happy: portraits/commanders/small/wulfar_portrait_happy.png
      sad: portraits/commanders/small/wulfar_portrait_sad.png
    cutscenePortrait: portraits/commanders/big/wulfar_portrait
    portraitOffset: [0, -45]
    namePlate: ui/character_select/charlabel/charlabel_outlaw.png
    themeSong: music/wulfar
    skinColour: typeII
    unitClassId: commander_flagship_wulfar
    selectionSound: wulfar/wulfarShoutUpForTheTask
    dialogueBoxVoice: ui/dialogue/textScrollWulfar
    
  - id: emeric_forced_red
    name: character_emeric_name
    title: character_emeric_title
    playable: false
    faction: cherrystone
    factionIndex: 1
    portrait:
      neutral: portraits/commanders/small/emeric_portrait_small.png
      happy: portraits/commanders/small/emeric_portrait_happy.png
      sad: portraits/commanders/small/emeric_portrait_sad.png
    cutscenePortrait: portraits/commanders/big/emeric_portrait_forced_red
    portraitOffset: [0, -25]
    namePlate: ui/character_select/charlabel/charlabel_emeric.png
    themeSong: music/emeric
    skinColour: typeVI
    unitClassId: commander_emeric
    selectionSound: emeric/emericShoutEducatedChoice
    dialogueBoxVoice: ui/dialogue/textScrollEmeric

  - id: outlaw_gang
    name: character_generic_outlaw_gang_name
    faction: outlaw
    playable: false
    portrait:
        happy: portraits/commanders/small/outlaw_poacher_portrait.png
        neutral: portraits/commanders/small/outlaw_soldier_portrait.png
        sad: portraits/commanders/small/outlaw_thief_portrait.png
        extra: portraits/commanders/small/outlaw_merfolk_portrait.png
    cutscenePortrait: portraits/commanders/big/outlaw_portrait
    portraitOffset: [0, 20]
    themeSong: music/hostile
    skinColour: typeII
    unitClassId: soldier
    dialogueBoxVoice: ui/dialogue/textScroll
    
  - id: vesper_gang
    name: character_generic_vesper_gang_name
    faction: outlaw
    playable: false
    portrait:
        happy: portraits/commanders/small/vesper_poacher_portrait.png
        neutral: portraits/commanders/small/vesper_soldier_portrait.png
        sad: portraits/commanders/small/vesper_thief_portrait.png
        extra: portraits/commanders/small/vesper_merfolk_portrait.png
    cutscenePortrait: portraits/commanders/big/outlaw_portrait
    portraitOffset: [0, 20]
    themeSong: music/hostile
    skinColour: typeII
    unitClassId: soldier
    dialogueBoxVoice: ui/dialogue/textScroll
    
  - id: generic_floran
    name: character_generic_floran_name
    faction: floran
    playable: false
    portrait:
      neutral: portraits/commanders/small/floran_portrait_small.png
      happy: portraits/commanders/small/floran_portrait_small.png
      sad: portraits/commanders/small/floran_portrait_small.png
    cutscenePortrait: portraits/commanders/big/floran_portrait
    themeSong: music/nuru
    skinColour: green
    unitClassId: soldier
    dialogueBoxVoice: ui/dialogue/textScroll
    
  - id: generic_heavensong
    name: character_generic_heavensong_name
    faction: heavensong
    playable: false
    portrait:
      neutral: portraits/commanders/small/heavensong_portrait_small.png
      happy: portraits/commanders/small/heavensong_portrait_small.png
      sad: portraits/commanders/small/heavensong_portrait_small.png
    cutscenePortrait: portraits/commanders/big/heavensong_portrait
    themeSong: music/koji
    skinColour: typeIII
    unitClassId: knight
    dialogueBoxVoice: ui/dialogue/textScroll
...