---
# List of Layer Types:
# base - drawn at the base layer, underneath mountains and rivers [grass effects, etc]
# ground - drawn below all units [flowers, rocks, etc.]
# units - sort together with units, base on the Y position, same as trees [flags etc.]
# sky - draws on top of all units [Clouds...?]

decorations:
#COVE WATERFALLS
  - id: cove_waterfall_down1
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_down01
  - id: cove_waterfall_down2
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_down02
  - id: cove_waterfall_down3
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_down03
  - id: cove_waterfall_left1
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_left01
  - id: cove_waterfall_left2
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_left02
  - id: cove_waterfall_left3
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_left03
  - id: cove_waterfall_right1
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_right01
  - id: cove_waterfall_right2
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_right02
  - id: cove_waterfall_right3
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_right03
  - id: cove_waterfall_up1
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_up01
  - id: cove_waterfall_up2
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_up02
  - id: cove_waterfall_up3
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/cove_waterfall_up03

#BIG DECO
  - id: shipExterior 
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/shipExterior
  - id: shipForeground
    layer: units
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/shipForeground
  - id: shipBridge
    layer: units
    animation:
      undefined: decoration/bigDeco/shipBridge
  - id: pirateShipExterior
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/pirateShipExterior
  - id: pirateShipForeground
    layer: units
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/pirateShipForeground
  - id: westMountain01
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/westMountain01
  - id: westMountain02
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/westMountain02
  - id: map4VoidMap
    layer: sky
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/map4VoidMap
  - id: map6VoidMap
    layer: sky
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/map6VoidMap
      
#Field 1
  - id: field01
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/field01
  - id: field01Layer01
    layer: units
    animation:
      undefined: decoration/bigDeco/field01Layer01
  - id: field01Layer02
    layer: units
    animation:
      undefined: decoration/bigDeco/field01Layer02
  - id: field01Layer03
    layer: units
    animation:
      undefined: decoration/bigDeco/field01Layer03
  - id: field01Layer04
    layer: units
    animation:
      undefined: decoration/bigDeco/field01Layer04

#Field 2
  - id: field02
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/field02
  - id: field02Layer01
    layer: units
    animation:
      undefined: decoration/bigDeco/field02Layer01
  - id: field02Layer02
    layer: units
    animation:
      undefined: decoration/bigDeco/field02Layer02
  - id: field02Layer03
    layer: units
    animation:
      undefined: decoration/bigDeco/field02Layer02
      
#Field 3
  - id: field03
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/field03
  - id: field03Layer01
    layer: units
    animation:
      undefined: decoration/bigDeco/field03Layer01
     
#Field 4
  - id: field04
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/field04
  - id: field04Layer01
    layer: units
    animation:
      undefined: decoration/bigDeco/field04Layer01
      
#Field 5
  - id: field05
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/field05
  - id: field05Layer01
    layer: units
    animation:
      undefined: decoration/bigDeco/field05Layer01
  - id: field05Layer02
    layer: units
    animation:
      undefined: decoration/bigDeco/field05Layer02
      
#Field 6
  - id: field06
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/bigDeco/field06
  - id: field06Layer01
    layer: units
    animation:
      undefined: decoration/bigDeco/field06Layer01
  - id: field06Layer02
    layer: units
    animation:
      undefined: decoration/bigDeco/field06Layer02
      
#Normal Deco
  - id: orangeField
    layer: ground
    animation:
      undefined: decoration/ground/orange_field
      
  - id: cabbageField
    layer: ground
    animation:
      undefined: decoration/ground/carbage_field
      
  - id: potatoField
    layer: ground
    animation:
      undefined: decoration/ground/potato_field
      
  - id: solidBarrel
    layer: units
    animation:
      undefined: decoration/unit/solidBarrel
  - id: windmill
    layer: units
    animation:
      undefined: decoration/unit/windmill
      
  - id: tileCover
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/ground/tileCover
      
  - id: NWCaveCorner
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/unit/NWCaveCorner
  - id: NECaveCorner
    layer: ground
    snapToGrid: true
    animation:
      undefined: decoration/unit/NECaveCorner
  - id: mountain_river01_cave
    layer: ground
    snapToGrid: true
    snapOffset: [-5, 10]
    animation:
      undefined: decoration/water/mountainriver01_cave
  - id: mountain_river01_cave_west
    layer: ground
    snapToGrid: true
    snapOffset: [8, -3]
    animation:
      undefined: decoration/water/mountainriver01_cave_west
  - id: mountain_river01_cave_east
    layer: ground
    snapToGrid: true
    snapOffset: [9, -3]
    animation:
      undefined: decoration/water/mountainriver01_cave_east
  - id: stalagmite01
    layer: units
    animation:
      undefined: decoration/water/stalagmite01
  - id: stalagmite02
    layer: units
    animation:
      undefined: decoration/water/stalagmite02
  - id: stalagmite_stalactite01
    layer: units
    animation:
      undefined: decoration/water/stalagmiteStalactite01
  - id: market_stand01
    layer: units
    animation:
      undefined: decoration/unit/marketStand01
  - id: market_stand02
    layer: units
    animation:
      undefined: decoration/unit/marketStand02
  - id: market_stand03
    layer: units
    animation:
      undefined: decoration/unit/marketStand03
  - id: market_stand04
    layer: units
    animation:
      undefined: decoration/unit/marketStand04
  - id: market_stand05
    layer: units
    animation:
      undefined: decoration/unit/marketStand05
  - id: anvil
    layer: units
    animation:
      undefined: decoration/unit/anvil
  - id: furnace
    layer: units
    animation:
      undefined: decoration/unit/furnace
  - id: furnaceSmall
    layer: units
    animation:
      undefined: decoration/unit/furnace_small
  - id: garland
    layer: units
    animation:
      undefined: decoration/unit/garland3d
  - id: garland01
    layer: units
    animation:
      undefined: decoration/unit/garland01
  - id: mangrove_small
    layer: units
    animation:
      undefined: decoration/unit/mangrove_small
  - id: mangrove_medium
    layer: units
    animation:
      undefined: decoration/unit/mangrove_medium
  - id: mangrove_big
    layer: units
    animation:
      undefined: decoration/unit/mangrove_big

  # flags
  - id: flag_cyan
    layer: units
    animation:
      undefined: decoration/unit/flag_cyan

  # battle standards
  - id: battlestandard_cyan
    layer: units
    animation:
      undefined: decoration/unit/battlestandard_cyan
      
#Alternate biomes

  # natural landscape decorations
  - id: breeze_alt
    layer: base
    animation:
      grass: decoration/ground/breeze_ice
      ice: decoration/ground/breeze_desert
      tropical: decoration/ground/breeze_desert
      desert: decoration/ground/breeze_grass
      volcano: decoration/ground/breeze_volcano     
  - id: rock0_alt
    layer: ground
    animation:
      grass: decoration/ground/rock0_ice
      ice: decoration/ground/rock0_desert
      tropical: decoration/ground/rock0_desert
      desert: decoration/ground/rock0_grass
      volcano: decoration/ground/rock0_volcano      
  - id: rock1_alt
    layer: ground
    animation:
      grass: decoration/ground/rock1_ice
      ice: decoration/ground/rock1_desert
      tropical: decoration/ground/rock1_desert
      desert: decoration/ground/rock1_grass
      volcano: decoration/ground/rock1_volcano   
  - id: rock2_alt
    layer: ground
    animation:
      grass: decoration/ground/rock2_ice
      ice: decoration/ground/rock2_desert
      tropical: decoration/ground/rock2_desert
      desert: decoration/ground/rock2_grass
      volcano: decoration/ground/rock2_volcano    
  - id: flowers1_alt
    layer: ground
    animation:
      grass: decoration/ground/flowers1_ice
      ice: decoration/ground/flowers1_desert
      tropical: decoration/ground/flowers1_desert
      desert: decoration/ground/flowers1_grass
      volcano: decoration/ground/flowers1_volcano     
  - id: flowers2_alt
    layer: ground
    animation:
      grass: decoration/ground/flowers2_ice
      ice: decoration/ground/flowers2_desert
      tropical: decoration/ground/flowers2_desert
      desert: decoration/ground/flowers2_grass
      volcano: decoration/ground/flowers2_volcano    
  - id: log1_alt
    layer: ground
    animation:
      grass: decoration/ground/log1_ice
      ice: decoration/ground/log1_desert
      tropical: decoration/ground/log1_desert
      desert: decoration/ground/log1_grass
      volcano: decoration/ground/log1_volcano       
  - id: log2_alt
    layer: ground
    animation:
      grass: decoration/ground/log2_ice
      ice: decoration/ground/log2_desert
      tropical: decoration/ground/log2_desert
      desert: decoration/ground/log2_grass
      volcano: decoration/ground/log2_volcano     
  - id: stump1_alt
    layer: units
    animation:
      grass: decoration/ground/stump1_ice
      ice: decoration/ground/stump1_desert
      tropical: decoration/ground/stump1_desert
      desert: decoration/ground/stump1_grass
      volcano: decoration/ground/stump1_desert      
  - id: monolith1_alt
    layer: units
    animation:
      grass: decoration/unit/monolith1_ice
      ice: decoration/unit/monolith1_desert
      tropical: decoration/unit/monolith1_desert
      desert: decoration/unit/monolith1_grass
      volcano: decoration/unit/monolith1_volcano    


  # ruins
  - id: ruin1_alt
    layer: units
    animation:
      grass: decoration/unit/ruin1_ice
      ice: decoration/unit/ruin1_desert
      tropical: decoration/unit/ruin1_desert
      desert: decoration/unit/ruin1_grass
      volcano: decoration/unit/ruin1_volcano     
  - id: ruin2_alt
    layer: units
    animation:
      grass: decoration/unit/ruin2_ice
      ice: decoration/unit/ruin2_desert
      tropical: decoration/unit/ruin2_desert
      desert: decoration/unit/ruin2_grass
      volcano: decoration/unit/ruin2_volcano    
  - id: ruin3_alt
    layer: units
    animation:
      grass: decoration/unit/ruin3_ice
      ice: decoration/unit/ruin3_desert
      tropical: decoration/unit/ruin3_desert
      desert: decoration/unit/ruin3_grass
      volcano: decoration/unit/ruin3_volcano        
  - id: ruin4_alt
    layer: units
    animation:
      grass: decoration/unit/ruin4_ice
      ice: decoration/unit/ruin4_desert
      tropical: decoration/unit/ruin4_desert
      desert: decoration/unit/ruin4_grass
      volcano: decoration/unit/ruin4_volcano      
  - id: ruin5_alt
    layer: units
    animation:
      grass: decoration/unit/ruin5_ice
      ice: decoration/unit/ruin5_desert
      tropical: decoration/unit/ruin5_desert
      desert: decoration/unit/ruin5_grass
      volcano: decoration/unit/ruin5_volcano  
  - id: ruin6_alt
    layer: units
    animation:
      grass: decoration/unit/ruin6_ice
      ice: decoration/unit/ruin6_desert
      tropical: decoration/unit/ruin6_desert
      desert: decoration/unit/ruin6_grass
      volcano: decoration/unit/ruin6_volcano      
  - id: ruin7_alt
    layer: ground
    animation:
      grass: decoration/ground/ruin7_ice
      ice: decoration/ground/ruin7_desert
      tropical: decoration/ground/ruin7_desert
      desert: decoration/ground/ruin7_grass
      volcano: decoration/ground/ruin7_volcano   
  - id: ruinground_alt
    layer: ground
    animation:
      grass: decoration/ground/ruinground_ice
      ice: decoration/ground/ruinground_desert
      tropical: decoration/ground/ruinground_desert
      desert: decoration/ground/ruinground_grass
      volcano: decoration/ground/ruinground_volcano
  - id: princessstatue_alt
    layer: units
    animation:
      grass: decoration/unit/princess_statue_ice
      ice: decoration/unit/princess_statue_desert
      tropical: decoration/unit/princess_statue_desert
      desert: decoration/unit/princess_statue_grass
      volcano: decoration/unit/princess_statue_volcano                                          
  # man-made objects
  - id: sign1_alt
    layer: units
    animation:
      grass: decoration/unit/sign1_ice
      ice: decoration/unit/sign1_desert
      tropical: decoration/unit/sign1_desert
      desert: decoration/unit/sign1_grass
      volcano: decoration/unit/sign1_desert        
  - id: sign2_alt
    layer: units
    animation:
      grass: decoration/unit/sign2_ice
      ice: decoration/unit/sign2_desert
      tropical: decoration/unit/sign2_desert
      desert: decoration/unit/sign2_grass
      volcano: decoration/unit/sign2_desert     
  - id: gravestone1_alt
    layer: units
    animation:
      grass: decoration/unit/gravestone1_ice
      ice: decoration/unit/gravestone1_desert
      tropical: decoration/unit/gravestone1_desert
      desert: decoration/unit/gravestone1_grass
      volcano: decoration/unit/gravestone1_volcano      
  - id: well_alt
    layer: units
    animation:
      grass: decoration/unit/well_ice
      ice: decoration/unit/well_desert
      tropical: decoration/unit/well_desert
      desert: decoration/unit/well_grass
      volcano: decoration/unit/well_desert      
  - id: chest1_alt
    layer: units
    animation:
      grass: decoration/unit/chest1_ice
      ice: decoration/unit/chest1_desert
      tropical: decoration/unit/chest1_desert
      desert: decoration/unit/chest1_grass
      volcano: decoration/unit/chest1_volcano     
  - id: scarecrow1_alt
    layer: units
    animation:
      grass: decoration/unit/scarecrow1_ice
      ice: decoration/unit/scarecrow1_desert
      tropical: decoration/unit/scarecrow1_desert
      desert: decoration/unit/scarecrow1_grass
      volcano: decoration/unit/scarecrow1_volcano 
  - id: pillar1_alt
    layer: units
    animation:
      grass: decoration/unit/pillar1_ice
      ice: decoration/unit/pillar1_desert
      tropical: decoration/unit/pillar1_desert
      desert: decoration/unit/pillar1_grass
      volcano: decoration/unit/pillar1_volcano     
  - id: pillar2_alt
    layer: units
    animation:
      grass: decoration/unit/pillar2_ice
      ice: decoration/unit/pillar2_desert
      tropical: decoration/unit/pillar2_desert
      desert: decoration/unit/pillar2_grass
      volcano: decoration/unit/pillar2_volcano  
  - id: barrel1_alt
    layer: units
    animation:
      grass: decoration/unit/barrel1_ice
      ice: decoration/unit/barrel1_desert
      tropical: decoration/unit/barrel1_desert
      desert: decoration/unit/barrel1_grass
      volcano: decoration/unit/barrel1_volcano    
  - id: crate1_alt
    layer: units
    animation:
      grass: decoration/unit/crate1_ice
      ice: decoration/unit/crate1_desert
      tropical: decoration/unit/crate1_desert
      desert: decoration/unit/crate1_grass
      volcano: decoration/unit/crate1_volcano        
  - id: hay_alt
    layer: units
    animation:
      grass: decoration/unit/hay_ice
      ice: decoration/unit/hay_desert
      tropical: decoration/unit/hay_desert
      desert: decoration/unit/hay_grass
      volcano: decoration/unit/hay_volcano     
...