---
# List of Layer Types:
# base - drawn at the base layer, underneath mountains and rivers [grass effects, etc]
# ground - drawn below all units [flowers, rocks, etc.]
# units - sort together with units, base on the Y position, same as trees [flags etc.]
# sky - draws on top of all units [Clouds...?]

decorations:
  # waterfalls and river connections
  - id: waterfall_down1
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_down01_grass
      dungeon: decoration/water/waterfall_down01_dungeon
      dungeon_lava: decoration/water/waterfall_down01_dungeon_lava
      ice: decoration/water/waterfall_down01_ice
      arctic: decoration/water/waterfall_down01_arctic
      arctic_blood: decoration/water/waterfall_down01_arctic_blood
      jungle: decoration/water/waterfall_down01_jungle
      tropical: decoration/water/waterfall_down01_tropical
      desert: decoration/water/waterfall_down01_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_down2
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_down02_grass
      dungeon: decoration/water/waterfall_down02_dungeon
      dungeon_lava: decoration/water/waterfall_down02_dungeon_lava
      ice: decoration/water/waterfall_down02_ice
      arctic: decoration/water/waterfall_down02_arctic
      arctic_blood: decoration/water/waterfall_down02_arctic_blood
      jungle: decoration/water/waterfall_down02_jungle
      tropical: decoration/water/waterfall_down02_tropical
      desert: decoration/water/waterfall_down02_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_down3
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_down03_grass
      dungeon: decoration/water/waterfall_down03_dungeon
      dungeon_lava: decoration/water/waterfall_down03_dungeon_lava
      ice: decoration/water/waterfall_down03_ice
      arctic: decoration/water/waterfall_down03_arctic
      arctic_blood: decoration/water/waterfall_down03_arctic_blood
      jungle: decoration/water/waterfall_down03_jungle
      tropical: decoration/water/waterfall_down03_tropical
      desert: decoration/water/waterfall_down03_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_left1
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_left01_grass
      dungeon: decoration/water/waterfall_left01_dungeon
      dungeon_lava: decoration/water/waterfall_left01_dungeon_lava
      ice: decoration/water/waterfall_left01_ice
      arctic: decoration/water/waterfall_left01_arctic
      arctic_blood: decoration/water/waterfall_left01_arctic_blood
      jungle: decoration/water/waterfall_left01_jungle
      tropical: decoration/water/waterfall_left01_tropical
      desert: decoration/water/waterfall_left01_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_left2
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_left02_grass
      dungeon: decoration/water/waterfall_left02_dungeon
      dungeon_lava: decoration/water/waterfall_left02_dungeon_lava
      ice: decoration/water/waterfall_left02_ice
      arctic: decoration/water/waterfall_left02_arctic
      arctic_blood: decoration/water/waterfall_left02_arctic_blood
      jungle: decoration/water/waterfall_left02_jungle
      tropical: decoration/water/waterfall_left02_tropical
      desert: decoration/water/waterfall_left02_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_left3
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_left03_grass
      dungeon: decoration/water/waterfall_left03_dungeon
      dungeon_lava: decoration/water/waterfall_left03_dungeon_lava
      ice: decoration/water/waterfall_left03_ice
      arctic: decoration/water/waterfall_left03_arctic
      arctic_blood: decoration/water/waterfall_left03_arctic_blood
      jungle: decoration/water/waterfall_left03_jungle
      tropical: decoration/water/waterfall_left03_tropical
      desert: decoration/water/waterfall_left03_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_right1
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_right01_grass
      dungeon: decoration/water/waterfall_right01_dungeon
      dungeon_lava: decoration/water/waterfall_right01_dungeon_lava
      ice: decoration/water/waterfall_right01_ice
      arctic: decoration/water/waterfall_right01_arctic
      arctic_blood: decoration/water/waterfall_right01_arctic_blood
      jungle: decoration/water/waterfall_right01_jungle
      tropical: decoration/water/waterfall_right01_tropical
      desert: decoration/water/waterfall_right01_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_right2
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_right02_grass
      dungeon: decoration/water/waterfall_right02_dungeon
      dungeon_lava: decoration/water/waterfall_right02_dungeon_lava
      ice: decoration/water/waterfall_right02_ice
      arctic: decoration/water/waterfall_right02_arctic
      arctic_blood: decoration/water/waterfall_right02_arctic_blood
      jungle: decoration/water/waterfall_right02_jungle
      tropical: decoration/water/waterfall_right02_tropical
      desert: decoration/water/waterfall_right02_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_right3
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_right03_grass
      dungeon: decoration/water/waterfall_right03_dungeon
      dungeon_lava: decoration/water/waterfall_right03_dungeon_lava
      ice: decoration/water/waterfall_right03_ice
      arctic: decoration/water/waterfall_right03_arctic
      arctic_blood: decoration/water/waterfall_right03_arctic_blood
      jungle: decoration/water/waterfall_right03_jungle
      tropical: decoration/water/waterfall_right03_tropical
      desert: decoration/water/waterfall_right03_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_up1
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_up01_grass
      dungeon: decoration/water/waterfall_up01_dungeon
      dungeon_lava: decoration/water/waterfall_up01_dungeon_lava
      ice: decoration/water/waterfall_up01_ice
      arctic: decoration/water/waterfall_up01_arctic
      arctic_blood: decoration/water/waterfall_up01_arctic_blood
      jungle: decoration/water/waterfall_up01_jungle
      tropical: decoration/water/waterfall_up01_tropical
      desert: decoration/water/waterfall_up01_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_up2
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_up02_grass
      dungeon: decoration/water/waterfall_up02_dungeon
      dungeon_lava: decoration/water/waterfall_up02_dungeon_lava
      ice: decoration/water/waterfall_up02_ice
      arctic: decoration/water/waterfall_up02_arctic
      arctic_blood: decoration/water/waterfall_up02_arctic_blood
      jungle: decoration/water/waterfall_up02_jungle
      tropical: decoration/water/waterfall_up02_tropical
      desert: decoration/water/waterfall_up02_desert
    noShadowMask: true
    depthScale: 0.0
  - id: waterfall_up3
    layer: above_water
    snapToGrid: true
    animation:
      grass: decoration/water/waterfall_up03_grass
      dungeon: decoration/water/waterfall_up03_dungeon
      dungeon_lava: decoration/water/waterfall_up03_dungeon_lava
      ice: decoration/water/waterfall_up03_ice
      arctic: decoration/water/waterfall_up03_arctic
      arctic_blood: decoration/water/waterfall_up03_arctic_blood
      jungle: decoration/water/waterfall_up03_jungle
      tropical: decoration/water/waterfall_up03_tropical
      desert: decoration/water/waterfall_up03_desert
    noShadowMask: true
    depthScale: 0.0
  - id: mountain_river01
    layer: ground
    snapToGrid: true
    snapOffset: [-5, 10]
    animation:
      grass: decoration/water/mountainriver01_grass
      dungeon: decoration/water/mountainriver01_dungeon
      dungeon_lava: decoration/water/mountainriver01_dungeon_lava
      ice: decoration/water/mountainriver01_ice
      arctic: decoration/water/mountainriver01_arctic
      arctic_blood: decoration/water/mountainriver01_arctic_blood
      jungle: decoration/water/mountainriver01_jungle
      tropical: decoration/water/mountainriver01_tropical
      desert: decoration/water/mountainriver01_desert
    noShadowMask: true
    depthScale: 0.0


  # hidden decorations only used in campaign map. deleting them will break map
  - id: waterfall_down2_lava
    hidden: true
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/waterfall_down02_lava
  - id: waterfall_down3_lava
    hidden: true
    layer: above_water
    snapToGrid: true
    animation:
      undefined: decoration/water/waterfall_down03_lava   


  # natural landscape decorations
  - id: breeze
    layer: base
    animation:
      grass: decoration/ground/breeze_grass
      dungeon: decoration/ground/breeze_dungeon
      dungeon_lava: decoration/ground/breeze_dungeon_lava
      ice: decoration/ground/breeze_ice
      arctic: decoration/ground/breeze_arctic
      jungle: decoration/ground/breeze_jungle
      desert: decoration/ground/breeze_desert
      tropical: decoration/ground/tropical/breeze_tropical
    noShadowMask: true
  - id: rock0
    layer: ground
    animation:
      grass: decoration/ground/rock0_grass
      dungeon: decoration/ground/rock0_dungeon
      dungeon_lava: decoration/ground/rock0_dungeon_lava
      ice: decoration/ground/rock0_ice
      arctic: decoration/ground/rock0_arctic
      jungle: decoration/ground/rock0_jungle
      desert: decoration/ground/rock0_desert    
      tropical: decoration/ground/tropical/rock0_tropical 
  - id: rock1
    layer: ground
    animation:
      grass: decoration/ground/rock1_grass
      dungeon: decoration/ground/rock1_dungeon
      dungeon_lava: decoration/ground/rock1_dungeon_lava
      ice: decoration/ground/rock1_ice
      arctic: decoration/ground/rock1_arctic
      jungle: decoration/ground/rock1_jungle
      desert: decoration/ground/rock1_desert  
      tropical: decoration/ground/tropical/rock1_tropical
  - id: rock2
    layer: ground
    animation:
      grass: decoration/ground/rock2_grass
      dungeon: decoration/ground/rock2_dungeon
      dungeon_lava: decoration/ground/rock2_dungeon_lava
      ice: decoration/ground/rock2_ice
      arctic: decoration/ground/rock2_arctic
      jungle: decoration/ground/rock2_jungle
      desert: decoration/ground/rock2_desert
      tropical: decoration/ground/tropical/rock2_tropical
  - id: flowers1
    layer: ground
    animation:
      grass: decoration/ground/flowers1_grass
      dungeon: decoration/ground/flowers1_dungeon
      dungeon_purple: decoration/ground/flowers1_dungeon_purple
      dungeon_lava: decoration/ground/flowers2_dungeon_lava
      ice: decoration/ground/flowers1_ice
      arctic: decoration/ground/flowers1_arctic
      jungle: decoration/ground/flowers1_jungle
      desert: decoration/ground/flowers1_desert     
      tropical: decoration/ground/flowers1_tropical  
  - id: flowers2
    layer: ground
    animation:
      grass: decoration/ground/flowers2_grass
      dungeon: decoration/ground/flowers2_dungeon
      dungeon_purple: decoration/ground/flowers2_dungeon_purple
      dungeon_lava: decoration/ground/flowers2_dungeon_lava
      ice: decoration/ground/flowers2_ice
      arctic: decoration/ground/flowers2_arctic
      jungle: decoration/ground/flowers2_jungle
      desert: decoration/ground/flowers2_desert  
      tropical: decoration/ground/flowers2_tropical
  - id: log1
    layer: ground
    animation:
      grass: decoration/ground/log1_grass
      dungeon: decoration/ground/log1_grass
      ice: decoration/ground/log1_ice
      arctic: decoration/ground/log1_arctic
      jungle: decoration/ground/log1_jungle
      desert: decoration/ground/log1_desert     
      tropical: decoration/ground/tropical/log1_tropical 
  - id: log2
    layer: ground
    animation:
      grass: decoration/ground/log2_grass
      dungeon: decoration/ground/log2_grass
      ice: decoration/ground/log2_ice
      arctic: decoration/ground/log2_arctic
      jungle: decoration/ground/log2_jungle
      desert: decoration/ground/log2_desert     
      tropical: decoration/ground/tropical/log2_tropical
  - id: stump1
    layer: units
    animation:
      grass: decoration/ground/stump1_grass
      dungeon: decoration/ground/stump1_grass
      ice: decoration/ground/stump1_ice
      arctic: decoration/ground/stump1_arctic
      jungle: decoration/ground/stump1_jungle
      desert: decoration/ground/stump1_desert  
      tropical: decoration/ground/tropical/stump1_tropical
      
  # natural water
  - id: reeds1
    layer: ground
    animation:
      grass: decoration/water/reeds1_grass
      dungeon: decoration/water/reeds1_dungeon
      dungeon_lava: decoration/water/reeds1_dungeon_lava
      ice: decoration/water/reeds1_ice
      arctic: decoration/water/reeds1_arctic
      arctic_blood: decoration/water/reeds1_arctic_blood
      jungle: decoration/water/reeds1_jungle
      tropical: decoration/water/reeds1_tropical
      desert: decoration/water/reeds1_desert
  - id: shark1
    layer: ground
    animation:
      grass: decoration/water/shark1_grass
      dungeon: decoration/water/shark1_dungeon
      dungeon_lava: decoration/water/shark1_dungeon_lava
      ice: decoration/water/shark1_ice
      arctic: decoration/water/shark1_arctic
      arctic_blood: decoration/water/shark1_arctic_blood
      jungle: decoration/water/shark1_jungle
      tropical: decoration/water/shark1_tropical
      desert: decoration/water/shark1_desert
  - id: waterrock1
    layer: ground
    animation:
      grass: decoration/water/waterrock1_grass
      dungeon: decoration/water/waterrock1_dungeon
      dungeon_lava: decoration/water/waterrock1_dungeon_lava
      ice: decoration/water/waterrock1_ice
      arctic: decoration/water/waterrock1_arctic
      arctic_blood: decoration/water/waterrock1_arctic_blood
      jungle: decoration/water/waterrock1_jungle
      tropical: decoration/water/waterrock1_tropical
      desert: decoration/water/waterrock1_desert
  - id: waterrock2
    layer: ground
    animation:
      grass: decoration/water/waterrock2_grass
      dungeon: decoration/water/waterrock2_dungeon
      dungeon_lava: decoration/water/waterrock1_dungeon_lava
      ice: decoration/water/waterrock2_ice
      arctic: decoration/water/waterrock2_arctic
      arctic_blood: decoration/water/waterrock2_arctic_blood
      jungle: decoration/water/waterrock2_jungle
      tropical: decoration/water/waterrock2_tropical
      desert: decoration/water/waterrock2_desert
  - id: waterrock3
    layer: ground
    animation:
      grass: decoration/water/waterrock3_grass
      dungeon: decoration/water/waterrock3_dungeon
      dungeon_lava: decoration/water/waterrock3_dungeon_lava
      ice: decoration/water/waterrock3_ice
      arctic: decoration/water/waterrock3_arctic
      arctic_blood: decoration/water/waterrock3_arctic_blood
      jungle: decoration/water/waterrock3_jungle
      tropical: decoration/water/waterrock3_tropical
      desert: decoration/water/waterrock3_desert
  - id: shipwreck1
    layer: ground
    animation:
      grass: decoration/water/shipwreck1_grass
      dungeon: decoration/water/shipwreck1_dungeon
      dungeon_lava: decoration/water/shipwreck1_dungeon_lava
      ice: decoration/water/shipwreck1_ice
      arctic: decoration/water/shipwreck1_arctic
      arctic_blood: decoration/water/shipwreck1_arctic_blood
      jungle: decoration/water/shipwreck1_jungle
      tropical: decoration/water/shipwreck1_tropical
      desert: decoration/water/shipwreck1_desert
  - id: driftwood1
    layer: ground
    animation:
      grass: decoration/water/driftwood1_grass
      dungeon: decoration/water/driftwood1_dungeon
      dungeon_lava: decoration/water/driftwood1_dungeon_lava
      ice: decoration/water/driftwood1_ice
      arctic: decoration/water/driftwood1_arctic
      arctic_blood: decoration/water/driftwood1_arctic_blood
      jungle: decoration/water/driftwood1_jungle
      tropical: decoration/water/driftwood1_tropical
      desert: decoration/water/driftwood1_desert
  - id: waterruin1
    layer: ground
    animation:
      grass: decoration/water/waterruin1_grass
      dungeon: decoration/water/waterruin1_dungeon
      dungeon_lava: decoration/water/waterruin1_dungeon_lava
      ice: decoration/water/waterruin1_ice
      arctic: decoration/water/waterruin1_arctic
      arctic_blood: decoration/water/waterruin1_arctic_blood
      jungle: decoration/water/waterruin1_jungle
      tropical: decoration/water/waterruin1_tropical
      desert: decoration/water/waterruin1_desert
  - id: waterruin2
    layer: ground
    animation:
      grass: decoration/water/waterruin2_grass
      dungeon: decoration/water/waterruin2_dungeon
      dungeon_lava: decoration/water/waterruin2_dungeon_lava
      ice: decoration/water/waterruin2_ice
      arctic: decoration/water/waterruin2_arctic
      arctic_blood: decoration/water/waterruin2_arctic_blood
      jungle: decoration/water/waterruin2_jungle
      tropical: decoration/water/waterruin2_tropical
      desert: decoration/water/waterruin2_desert
  - id: waterruin3
    layer: ground
    animation:
      grass: decoration/water/waterruin3_grass
      dungeon: decoration/water/waterruin3_dungeon
      dungeon_lava: decoration/water/waterruin3_dungeon_lava
      ice: decoration/water/waterruin3_ice
      arctic: decoration/water/waterruin3_arctic
      arctic_blood: decoration/water/waterruin3_arctic_blood
      jungle: decoration/water/waterruin3_jungle
      tropical: decoration/water/waterruin3_tropical
      desert: decoration/water/waterruin3_desert
  - id: waterruin4
    layer: ground
    animation:
      grass: decoration/water/waterruin4_grass
      dungeon: decoration/water/waterruin4_dungeon
      dungeon_lava: decoration/water/waterruin4_dungeon_lava
      ice: decoration/water/waterruin4_ice
      arctic: decoration/water/waterruin4_arctic
      arctic_blood: decoration/water/waterruin4_arctic_blood
      jungle: decoration/water/waterruin4_jungle
      tropical: decoration/water/waterruin4_tropical
      desert: decoration/water/waterruin4_desert
  - id: waterruin5
    layer: ground
    animation:
      grass: decoration/water/waterruin5_grass
      dungeon: decoration/water/waterruin5_dungeon
      dungeon_lava: decoration/water/waterruin5_dungeon_lava
      ice: decoration/water/waterruin5_ice
      arctic: decoration/water/waterruin5_arctic
      arctic_blood: decoration/water/waterruin5_arctic_blood
      jungle: decoration/water/waterruin5_jungle
      tropical: decoration/water/waterruin5_tropical
      desert: decoration/water/waterruin5_desert
                            
 # natural lava
  - id: lavarock1
    hidden: true
    layer: ground
    animation:
      undefined: decoration/water/lavarock1
  - id: lavarock2
    hidden: true
    layer: ground
    animation:
      undefined: decoration/water/lavarock2   
  - id: lavarock3
    hidden: true
    layer: ground
    animation:
      undefined: decoration/water/lavarock3
  - id: lavarock4
    hidden: true
    layer: ground
    animation:
      undefined: decoration/water/lavarock4
  - id: lavabubble
    hidden: true
    layer: ground
    animation:
      undefined: decoration/water/lavabubble      
...