---

factions:
  - id: outlaw
    name: faction_name_outlaw
    stdColour: black
    altColour: cyan
    skinColours: [ "typeII", "typeIII", "typeIV", "typeV", "typeVI" ]
    bannerForeground: backgrounds/banners/banner_outlaw_FG
    bannerBackground: backgrounds/banners/banner_outlaw_BG
    rivalFaction: cherrystone
...