---

music:
  - id: tavern_distant
    name: music_name_tavern_distant
    audioEvent: music/tavernDistant
    
  - id: bar_ambiance_distant
    name: music_name_bar_ambience_distant
    audioEvent: environmental/barAmbienceDistant
    isAmbience: true
    
  - id: ocean_ambience
    name: music_name_ocean_ambience
    audioEvent: environmental/oceanAmbience
...
