---
terrains:
  - id: brush_invis_icon
    name: terrain_name_brush
    defenceBonus: 0
    movementCost: {}
    movementGroupType: [land]
    placeable: true
    tilesets:
      0: [plains, plains_alt]
      1: brush_invis

  - id: invisibleBlockerOcean_icon
    name: terrain_name_cabin
    defenceBonus: 0
    movementCost: {}
    movementGroupType: [land]
    placeable: true
    tilesets:
      0: sea
      1: ocean
      2: invisible_blocker_ocean

  - id: invisibleWallOcean_icon
    name: terrain_name_hull
    defenceBonus: 0
    movementCost: {}
    movementGroupType: [land]
    placeable: true
    tilesets:
      0: sea
      1: ocean
      2: invisible_wall_ocean

  - id: invisibleWallSea_icon
    name: terrain_name_hull
    defenceBonus: 0
    movementCost: {}
    movementGroupType: [land]
    placeable: true
    tilesets:
      0: sea
      1: invisible_wall_sea


      
...