---

terrains:
  - id: plains
    name: terrain_name_plains
    defenceBonus: 1
    movementCost:
      walking: 1
      riding: 1
      flying: 1
      hovering: 1
      wheels: 2
      amphibious: 2
      airphibious: 1
      land_building: 1
      indoor_building: 1
    movementGroupType: [land]
    placeable: true
    tilesets:
      0: plains

  - id: road
    name: terrain_name_road
    defenceBonus: 0
    movementCost:
      walking: 1
      riding: 1
      flying: 1
      hovering: 1
      wheels: 1
      amphibious: 2
      airphibious: 1
      land_building: 1
      indoor_building: 1
    movementGroupType: [land]
    placeable: true
    tilesets:
      0: [plains, plains_alt]
      2: road
    wang:
      complementary: true
      adjacencies: [bridge, abyss_bridge]

  - id: forest
    name: terrain_name_forest
    defenceBonus: 3
    movementCost:
      walking: 2
      riding: 3
      flying: 1
      hovering: 1
      amphibious: 3
      airphibious: 1
    movementGroupType: [land]
    placeable: true
    visionBlocking: true
    fowCover: true
    tilesets:
      0: [plains, plains_alt]
      1: forest

  - id: mountain
    name: terrain_name_mountain
    defenceBonus: 4
    movementCost:
      walking: 3
      flying: 1
      hovering: 1
      airphibious: 1
    movementGroupType: [land]
    placeable: true
    visionBlocking: true
    sightBonus: 2
    tilesets:
      0: [plains, rough, plains_alt]
      1: mountain

  - id: cobblestone
    name: terrain_name_cobblestone
    defenceBonus: 2
    movementCost:
      walking: 1
      riding: 1
      amphibious: 2
      hovering: 1
      land_building: 1
      indoor_building: 1
      airphibious: 1
    movementGroupType: [land]
    cantStop: [flying]
    placeable: true
    indoor: true
    tilesets:
      0: [plains, rough, plains_alt]
      1: cobblestone
    wang:
      complementary: true

  - id: carpet
    name: terrain_name_carpet
    defenceBonus: 2
    movementCost:
      walking: 1
      riding: 1
      amphibious: 2
      airphibious: 1
      hovering: 1
      land_building: 1
      indoor_building: 1
    movementGroupType: [land]
    placeable: true
    indoor: true
    tilesets:
      0: [plains, rough, plains_alt]
      1: cobblestone
      2: carpet
    wang:
      complementary: true

  - id: wall
    name: terrain_name_wall
    defenceBonus: 0
    movementCost: {}
    movementGroupType: [land]
    visionBlocking: true
    placeable: true
    tilesets:
      0: [plains, rough, plains_alt]
      1: cobblestone
      2: wall
    wang:
      complementary: true

  - id: bridge
    name: terrain_name_bridge
    defenceBonus: 0
    movementCost:
      walking: 1
      riding: 1
      flying: 1
      hovering: 1
      wheels: 1
      amphibious: 1
      sailing: 2
      land_building: 1
      indoor_building: 1
      airphibious: 1
      river_sailing: 1
    cantStop: [sailing, river_sailing]
    movementGroupType: [land]
    placeable: true
    tilesets: 
      0: [plains, plains_alt, street, beach, cave_beach sea, quay, cave_sea, river, cave_river, waterfall]
      2: bridge
    wang:
      blend: true
      blendTo: [plains, road, cave_road, street, forest, forest_cut, mountain, cobblestone]
      complementary: true
      canRenderWater: true
      adjacencies: [road, cave_road, street]

  - id: sea
    name: terrain_name_sea
    biomeNames:
      volcano: terrain_name_sea_lava
    biomeDescriptions:
      volcano: terrain_description_lava
    cantStop: [airphibious]
    defenceBonus: 1
    movementCost:
      sailing: 2
      flying: 1
      hovering: 1
      amphibious: 1
      sea_building: 1
      river_sea_building: 1
      airphibious: 1
      river_sailing: 1
    biomeMovementCosts:
      volcano:
        flying: 1
        hovering: 1
    movementGroupType: [water]
    placeable: true
    tilesets:
      0: sea
    wang:
      complementary: true
      canRenderWater: true
      adjacencies: [beach, ocean, reef, river, bridge, quay, invisible_wall_sea, invisible_blocker_ocean, cave_sea, cave_river, cave_reef, cave_beach]

  - id: ocean
    name: terrain_name_ocean
    biomeNames:
      volcano: terrain_name_ocean_lava
    biomeDescriptions:
      volcano: terrain_description_lava
    defenceBonus: 0
    cantStop: [airphibious]
    movementCost:
      river_sailing: 1
      sailing: 1
      flying: 1
      hovering: 1
      sea_building: 1
      river_sea_building: 1
      airphibious: 1
      amphibious: 2
    biomeMovementCosts:
      volcano:
        flying: 1
        hovering: 1
      dungeon:
        flying: 1
        hovering: 1
      dungeon_lava:
        flying: 1
        hovering: 1
    movementGroupType: [water]
    placeable: true
    tilesets:
      0: sea
      1: ocean
    wang:
      complementary: true
      canRenderWater: true
      adjacencies: [invisible_blocker_ocean, invisible_wall_ocean]

  - id: reef
    name: terrain_name_reef
    biomeNames:
      volcano: terrain_name_reef_lava
    biomeDescriptions:
      volcano: terrain_description_lava
    cantStop: [airphibious]
    defenceBonus: 2
    movementCost:
      sailing: 4
      flying: 1
      hovering: 1
      amphibious: 1
      airphibious: 1
      river_sailing: 2
    biomeMovementCosts:
      volcano:
        flying: 1
        hovering: 1
    movementGroupType: [water]
    placeable: true
    fowCover: true
    tilesets: 
      0: [sea, quay]
      2: reef
    wang:
      complementary: true
      canRenderWater: true
      adjacencies: [sea, cave_sea, quay, river, cave_river, beach, cave_beach, ocean, invisible_blocker_ocean, invisible_wall_ocean, cave_reef]

  - id: river
    name: terrain_name_river
    biomeNames:
      volcano: terrain_name_river_lava
    biomeDescriptions:
      volcano: terrain_description_lava
    defenceBonus: -2
    movementCost:
      walking: 2
      riding: 4
      flying: 1
      hovering: 1
      amphibious: 1
      airphibious: 1
      sailing: 2
      river_sailing: 1
      river_building: 1
      river_sea_building: 1
    biomeMovementCosts:
      volcano:
        flying: 1
        hovering: 1
      dungeon_lava:
        flying: 1
        hovering: 1
    movementGroupType: [land, water]
    placeable: true
    tilesets:
      0: river
    wang:
      complementary: true
      canRenderWater: true
      adjacencies: [sea, cave_sea, quay, cave_river, waterfall, beach, cave_beach, ocean, invisible_blocker_ocean, invisible_wall_ocean, reef, cave_reef]

  - id: beach
    name: terrain_name_beach
    defenceBonus: -1
    movementCost:
      sailing: 3
      river_sailing: 1
      walking: 1
      riding: 2
      flying: 1
      hovering: 1
      airphibious: 1
      amphibious: 1
      sea_building: 1
      river_sea_building: 1
    biomeMovementCosts:
      volcano:
        walking: 1
        riding: 1
        flying: 1
        hovering: 1
        amphibious: 2
    movementGroupType: [land, water]
    placeable: true
    tilesets:
      0: beach
    wang:
      blend: true
      blendTo: [sea]
      complementary: true
      canRenderWater: true
      adjacencies: [sea, quay, cave_sea, river, cave_river, ocean, invisible_blocker_ocean, invisible_wall_ocean, reef, cave_reef]

  - id: sky
    name: terrain_name_sky
    defenceBonus: 0
    movementCost:
      flying: 1
      hovering: 1
    movementGroupType: [air]
    placeable: false

  - id: city
    name: structure_name_city
    defenceBonus: 4
    movementCost:
      walking: 1
      riding: 1
      flying: 1
      hovering: 1
      wheels: 1
      amphibious: 2
    movementGroupType: [land]
    placeable: false

  - id: volcano
    name: terrain_name_volcano
    defenceBonus: 0
    movementCost: {}
    movementGroupType: [land]
    placeable: true
    hidden: true
    tilesets:
      0: volcano
...