---
verbs:
  - id: wait_ai
    icon: ui/icons/unit_action_icon_wait.png
    name: ui_unit_verbs_wait
    targetColour: target
    targetOutlineColour: target_outline
    targetted: false
    aiUses: true
    scriptName: verbs/wait_ai
    
  - id: attack_AI
    icon: ui/icons/unit_action_icon_attack.png
    name: ui_unit_verbs_attack
    targetColour: attack_target
    targetOutlineColour: attack_target_outline
    targetted: true
    directTarget: true
    preExecute: true
    # description: ui_unit_verbs_attack_description
    scriptName: verbs/attack_AI

  - id: capture_AI
    icon: ui/icons/unit_action_icon_capture.png
    name: ui_unit_verbs_capture
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    directTarget: true
    scriptName: verbs/capture_AI

  - id: mini_groove_teleport
    icon: ui/icons/grooves/unit_action_icon_teleport_tier_0.png
    name: mini_groove_name_teleport
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    scriptName: verbs/mini_groove_teleport
    
  - id: groove_smoke_screen
    icon: ui/icons/grooves/unit_action_icon_smoke_tier_1.png
    name: groove_name_smoke_screen
    targetColour: target
    targetOutlineColour: target_outline
    splashOutlineColour: heal_outline
    targetted: true
    hasCustomSplash: true
    scriptName: verbs/groove_smoke_screen_extra

  - id: mini_groove_putt
    icon: ui/icons/grooves/unit_action_icon_putt_tier_0.png
    name: mini_groove_name_putt
    targetColour: target
    targetOutlineColour: target_outline
    targetDisplayColour: attack_target
    targetDisplayOutlineColour: attack_target_outline
    preExecute: true
    targetted: true
    directTarget: true
    scriptName: verbs/mini_groove_putt

  - id: groove_golf
    icon: ui/icons/grooves/unit_action_icon_golf_tier_1.png
    name: groove_name_golf
    targetColour: target
    targetOutlineColour: target_outline
    targetDisplayColour: attack_target
    targetDisplayOutlineColour: attack_target_outline
    preExecute: true
    targetted: true
    directTarget: true
    scriptName: verbs/groove_golf_extra

  - id: groove_no_groove
    icon: ui/icons/grooves/unit_action_icon_inspire.png
    name: ui_unit_verbs_pick_up_crown
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/groove_no_groove

  - id: take_crown
    icon: ui/icons/grooves/unit_action_icon_inspire.png
    name: ui_unit_verbs_pick_up_crown
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    scriptName: verbs/take_crown

  - id: hand_over_crown
    icon: ui/icons/grooves/unit_action_icon_inspire.png
    name: ui_unit_verbs_hand_over_crown
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    directTarget: true
    scriptName: verbs/hand_over_crown
    
  - id: item_throw
    icon: ui/icons/unit_action_icon_merge.png
    name: item_verb_throw_crown_name
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
#    directTarget: true
    scriptName: verbs/item_throw

  - id: item_kick
    icon: ui/icons/unit_action_icon_kick.png
    name: item_verb_kick_name
    targetColour: attack_target
    targetOutlineColour: attack_target_outline
    targetted: true
    hasTargetArrows: true
#    directTarget: true
    scriptName: verbs/item_kick

  - id: throw_item
    icon: ui/icons/unit_action_icon_merge.png
    name: ui_unit_verbs_throw_crown
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
#    directTarget: true
    scriptName: verbs/throw_crown

  - id: death
    icon: ui/icons/grooves/unit_action_icon_bomb.png
    name: ui_unit_verbs_explode
    splashOutlineColour: attack_target_outline
    scriptName: verbs/death

  - id: pirate_steal
    icon: ui/icons/unit_action_icon_steal.png
    name: ui_unit_verbs_steal
    targetColour: attack_target
    targetOutlineColour: target_outline
    targetted: true
    directTarget: true                                  # This verb targets a specific unit
    scriptName: verbs/pirate_steal
    aiUses: true
    
  - id: pirate_deposit
    icon: ui/icons/unit_action_icon_deposit.png
    name: ui_unit_verbs_deposit
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    directTarget: true                                  # This verb targets a specific unit
    scriptName: verbs/pirate_deposit
    aiUses: true
    
  - id: pirate_claim
    icon: ui/icons/unit_action_icon_capture.png
    name: ui_unit_verbs_claim
    targetColour: target
    scriptName: verbs/pirate_claim

    
  - id: mini_groove_ram
    icon: ui/icons/grooves/unit_action_icon_ram_tier_0.png
    name: mini_groove_name_ram
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    scriptName: verbs/mini_groove_ram

  - id: groove_broadside
    icon: ui/icons/grooves/unit_action_icon_broadside_tier_1.png
    name: groove_name_broadside
    targetColour: target
    targetOutlineColour: attack_target_outline
    targetDisplayOutlineColour: attack_target_outline
    targetted: true
    preExecute: true
    scriptName: verbs/groove_broadside
    
  - id: mini_groove_gun
    icon: ui/icons/grooves/unit_action_icon_gun_tier_0.png
    name: mini_groove_name_gun
    targetColour: target
    targetOutlineColour: target_outline
    targetDisplayColour: attack_target
    targetDisplayOutlineColour: attack_target_outline
    preExecute: true
    scriptName: verbs/mini_groove_gun

  - id: mini_groove_split
    icon: ui/icons/grooves/unit_action_icon_split_tier_0.png
    name: mini_groove_name_split
    targetColour: target
    targetOutlineColour: target_outline
    targetDisplayColour: attack_target
    targetDisplayOutlineColour: attack_target_outline
    targetted: true
    preExecute: true
    scriptName: verbs/mini_groove_split

  - id: groove_area_damage_rival
    icon: ui/icons/grooves/unit_action_icon_shield.png
    name: groove_name_area_damage_rival
    targetColour: target
    targetOutlineColour: target_outline
    targetDisplayOutlineColour: attack_target_outline
    targetted: true
    scriptName: verbs/groove_area_damage_rival
    splashOutlineColour: attack_target_outline
    splashRadius: 3

  - id: groove_alert_area
    icon: ui/icons/grooves/unit_action_icon_shield.png
    name: groove_name_alert_area
    targetColour: target
    targetOutlineColour: target_outline
    targetDisplayOutlineColour: attack_target_outline
    targetted: true
    scriptName: verbs/groove_alert_area
    splashOutlineColour: attack_target_outline
    splashRadius: 2

  - id: groove_morale_boost
    icon: ui/icons/grooves/unit_action_icon_en_garde_tier_1.png
    name: groove_name_morale_boost
    targetColour: target
    targetOutlineColour: target_outline
    splashOutlineColour: heal_outline
    targetted: true
    splashRadius: 2
    scriptName: verbs/groove_morale_boost

  - id: rescue
    icon: ui/icons/grooves/unit_action_icon_inspire.png
    name: ui_unit_verbs_rescue
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    directTarget: true
    scriptName: verbs/rescue

  - id: hire
    icon: ui/icons/grooves/unit_action_icon_inspire.png
    name: ui_unit_verbs_hire
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    targetted: true
    directTarget: true
    scriptName: verbs/hire

  - id: refreshments
    icon: ui/icons/unit_action_icon_give_drink.png
    name: ui_unit_verbs_upgrade
    targetColour: target
    targetOutlineColour: target_outline
    targetDisplayColour: target
    targetDisplayOutlineColour: target_outline
    preExecute: true
    targetted: false
    scriptName: verbs/upgrade
    
...